DEFINE RECORD CDD$TOP.OE.OE_REGLINE_ARC

        DESCRIPTION IS /*Sales Order Line Archive File*/.

        OE_REGLINE_ARC_CDD STRUCTURE.

        END OE_REGLINE_ARC_CDD STRUCTURE.

END OE_REGLINE_ARC.
