DEFINE RECORD CDD$TOP.OE.OE_REGHEADER_ARC

        DESCRIPTION IS /*Sales Order Header Archive File*/.

        OE_REGHEADER_ARC_CDD STRUCTURE.

        END OE_REGHEADER_ARC_CDD STRUCTURE.

END OE_REGHEADER_ARC.
