1	! Program to set THISHOUS to HOURS in BL_PRODOPER
	!
	! Author:
	!
	!	02/20/95 - Kevin Handy

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[BM.OPEN]BM_PRODOPER.HB"
	MAP (BM_PRODOPER) BM_PRODOPER_CDD BM_PRODOPER

100	%INCLUDE "SOURCE:[BM.OPEN]BM_PRODOPER.MOD"

1000	FIND #BM_PRODOPER.CH%, KEY #0% GE "0"

1100	GET #BM_PRODOPER.CH%

1120 !	IF LEFT(BM_PRODOPER::PRODUCT, 1%) = "0"
 !	THEN

	IF BM_PRODOPER::THISHOURS <> BM_PRODOPER::HOURS
	THEN
		BM_PRODOPER::THISHOURS = BM_PRODOPER::HOURS

		UPDATE #BM_PRODOPER.CH%

		PRINT BM_PRODOPER::PRODUCT
	END IF

	GOTO 1100

1200	CLOSE #BM_PRODOPER.CH%

32767	END
