1	!
	!++
	! Description:
	!
	!	MERGE two PC_PRICE master files together.
	!	BE CAREFUL THAT THIS IS WHAT YOU REALLY WANT TO DO
	!
	! History:
	!
	!	04/01/2002 - Kevin Handy
	!--

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[PC.OPEN]PC_PRICE.HB"
	MAP (PC_PRICE) PC_PRICE_CDD PC_PRICE

100	!
	! Open up product master file
	!
	%INCLUDE "SOURCE:[PC.OPEN]PC_PRICE.OPN"
	PC_PRICE_PLAZA.CH% = PC_PRICE.CH%
	RESET #PC_PRICE_PLAZA.CH%
	PC_PRICE.CH% = 0%

200	!
	! Open up other product file
	!
	PC_PRICE.DEV$ = "$DISK2:[ROBSON]"
	%INCLUDE "SOURCE:[PC.OPEN]PC_PRICE.MOD"
	PC_PRICE_MARCO.CH% = PC_PRICE.CH%
	PC_PRICE.CH% = 0%

1000	!
	! Search for the next "O" category item
	!
	WHEN ERROR IN
		GET #PC_PRICE_PLAZA.CH%, REGARDLESS
	USE
		CONTINUE 2000
	END WHEN

1010	WHEN ERROR IN
		PUT #PC_PRICE_MARCO.CH%
	USE
		PRINT "FAILED: " + PC_PRICE::PRODUCT_NUM + " " + &
			PC_PRICE::LOCATION
		CONTINUE 1900
	END WHEN

	PRINT "ADDED: " + &
		PC_PRICE::PRODUCT_NUM + " " + &
		PC_PRICE::LOCATION

1900	GOTO 1000

2000	!

32767	END
