1	!
	!++
	! Description:
	!
	!	MERGE two PD_ACCOUNT master files together.
	!	BE CAREFUL THAT THIS IS WHAT YOU REALLY WANT TO DO
	!
	! History:
	!
	!	04/01/2002 - Kevin Handy
	!--

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[PD.OPEN]PD_ACCOUNT.HB"
	MAP (PD_ACCOUNT) PD_ACCOUNT_CDD PD_ACCOUNT

100	!
	! Open up product master file
	!
	%INCLUDE "SOURCE:[PD.OPEN]PD_ACCOUNT.OPN"
	PD_ACCOUNT_PLAZA.CH% = PD_ACCOUNT.CH%
	RESET #PD_ACCOUNT_PLAZA.CH%
	PD_ACCOUNT.CH% = 0%

200	!
	! Open up other product file
	!
	PD_ACCOUNT.DEV$ = "$DISK2:[ROBSON]"
	%INCLUDE "SOURCE:[PD.OPEN]PD_ACCOUNT.CRE"
	PD_ACCOUNT_MARCO.CH% = PD_ACCOUNT.CH%
	PD_ACCOUNT.CH% = 0%

1000	!
	! Search for the next "O" category item
	!
	WHEN ERROR IN
		GET #PD_ACCOUNT_PLAZA.CH%, REGARDLESS
	USE
		CONTINUE 2000
	END WHEN

1010	WHEN ERROR IN
		PUT #PD_ACCOUNT_MARCO.CH%
	USE
		PRINT "FAILED: " + PD_ACCOUNT::PRODTYPE
		CONTINUE 1900
	END WHEN

	PRINT "ADDED: " + &
		PD_ACCOUNT::PRODTYPE + " " + &
		PD_ACCOUNT::LOCATION

1900	GOTO 1000

2000	!

32767	END
