1	!
	!++
	! Description:
	!
	!	MERGE two IC_35HISTORY master files together.
	!	BE CAREFUL THAT THIS IS WHAT YOU REALLY WANT TO DO
	!
	! History:
	!
	!	04/10/2002 - Kevin Handy
	!--

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[IC.OPEN]IC_35HISTORY.HB"
	MAP (IC_35HISTORY) IC_35HISTORY_CDD IC_35HISTORY

	LINPUT "Year (YYYYPP) "; YYYY$

100	!
	! Open up product master file
	!
	%INCLUDE "SOURCE:[IC.OPEN]IC_35HISTORY.OPN"
	IC_35HISTORY_PLAZA.CH% = IC_35HISTORY.CH%
	RESET #IC_35HISTORY_PLAZA.CH%
	IC_35HISTORY.CH% = 0%

200	!
	! Open up other product file
	!
	IC_35HISTORY.DEV$ = "$DISK2:[ROBSON]"
	%INCLUDE "SOURCE:[IC.OPEN]IC_35HISTORY.MOD"
	IC_35HISTORY_MARCO.CH% = IC_35HISTORY.CH%
	IC_35HISTORY.CH% = 0%

1000	!
	! Search for the next "O" category item
	!
	WHEN ERROR IN
		GET #IC_35HISTORY_PLAZA.CH%, REGARDLESS
	USE
		CONTINUE 2000
	END WHEN

1010	WHEN ERROR IN
		PUT #IC_35HISTORY_MARCO.CH%
	USE
		PRINT "FAILED: " + IC_35HISTORY::PRODUCT
		CONTINUE 1900
	END WHEN

	PRINT "ADDED: " + &
		IC_35HISTORY::PRODUCT + " " + &
		IC_35HISTORY::TRANSTYPE

1900	GOTO 1000

2000	!

32767	END
