1	!
	!++
	! Description:
	!
	!	MERGE two IC_35BALANCE master files together.
	!	BE CAREFUL THAT THIS IS WHAT YOU REALLY WANT TO DO
	!
	! History:
	!
	!	04/01/2002 - Kevin Handy
	!--

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[IC.OPEN]IC_35BALANCE.HB"
	MAP (IC_35BALANCE) IC_35BALANCE_CDD IC_35BALANCE

100	!
	! Open up product master file
	!
	%INCLUDE "SOURCE:[IC.OPEN]IC_35BALANCE.OPN"
	IC_35BALANCE_PLAZA.CH% = IC_35BALANCE.CH%
	RESET #IC_35BALANCE_PLAZA.CH%
	IC_35BALANCE.CH% = 0%

200	!
	! Open up other product file
	!
	IC_35BALANCE.DEV$ = "$DISK2:[ROBSON]"
	%INCLUDE "SOURCE:[IC.OPEN]IC_35BALANCE.MOD"
	IC_35BALANCE_MARCO.CH% = IC_35BALANCE.CH%
	IC_35BALANCE.CH% = 0%

1000	!
	! Search for the next "O" category item
	!
	WHEN ERROR IN
		GET #IC_35BALANCE_PLAZA.CH%, REGARDLESS
	USE
		CONTINUE 2000
	END WHEN

1010	WHEN ERROR IN
		PUT #IC_35BALANCE_MARCO.CH%
	USE
		PRINT "FAILED: " + IC_35BALANCE::PRODUCT
		CONTINUE 1900
	END WHEN

	PRINT "ADDED: " + &
		IC_35BALANCE::PRODUCT + " " + &
		IC_35BALANCE::LOCATION + " " + &
		IC_35BALANCE::TRANSTYPE

1900	GOTO 1000

2000	!

32767	END
