1	!
	!++
	! Description:
	!
	!	Special program to change 'MP' type items in the
	!	inventory master file to 'DR' when they have no
	!	components under them.
	!
	! History:
	!
	!	12/29/2003 - Kevin Handy
	!		Original version
	!
	!--

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[PD.OPEN]PD_PRODUCT.HB"
	MAP (PD_PRODUCT) PD_PRODUCT_CDD PD_PRODUCT

	%INCLUDE "SOURCE:[BM.OPEN]BM_RELATION.HB"
	MAP (BM_RELATION) BM_RELATION_CDD BM_RELATION

	DECLARE RFA GEBACK

100	!
	! Open up product master file
	!
	%INCLUDE "SOURCE:[PD.OPEN]PD_PRODUCT.MOD"

	RESET #PD_PRODUCT.CH%

200	%INCLUDE "SOURCE:[BM.OPEN]BM_RELATION.OPN"

1000	!
	! Search for the next "O" category item
	!
	GET #PD_PRODUCT.CH%

	IF PD_PRODUCT::PROD_TYPE <> "DR" OR PD_PRODUCT::SSTATUS <>"A"
	THEN
		GOTO 1000
	END IF

	THIS_PRODUCT$ = PD_PRODUCT::PRODUCT_NUM + ""

	WHEN ERROR IN
		FIND #BM_RELATION.CH%, KEY #1% EQ THIS_PRODUCT$
	USE
		!
		! No PARENTS, SKIP it.
		!
		CONTINUE 1000 IF ERR = 155%
		PRINT ERR, ERL
		STOP
		CONTINUE 1000
	END WHEN

1020	GEBACK = GETRFA(PD_PRODUCT.CH%)

1030	WHEN ERROR IN
		GET #BM_RELATION.CH%, REGARDLESS
	USE
		!
		! Assume nothing found
		!
		CONTINUE 1090
	END WHEN

	IF BM_RELATION::COMPONENT = THIS_PRODUCT$
	THEN
		WHEN ERROR IN
			GET #PD_PRODUCT.CH%, &
				KEY #0% EQ BM_RELATION::PRODUCT, &
				REGARDLESS
		USE
			CONTINUE 1090
		END WHEN

		!
		! Found one
		!
		GOTO 1100 IF PD_PRODUCT::PROD_TYPE = "OP"

		GOTO 1030
	END IF

1090	GET #PD_PRODUCT.CH%, RFA GEBACK

	GOTO 1000

1100	!
	! Change products
	!
	GET #PD_PRODUCT.CH%, RFA GEBACK

	PRINT PD_PRODUCT::PRODUCT_NUM

	PD_PRODUCT::PROD_TYPE = "SA"
	UPDATE #PD_PRODUCT.CH%

	GOTO 1090

32767	END
