1	!
	! Special program to remove items from a "Fill" cycle count
	! journal based on items existing in a adjustment report.
	!
	! History
	!
	!	11/06/2001 - Kevin Handy
	!		Original version
	!
	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[IC.OPEN]IC_JOURCOUNT.HB"
	MAP (IC_JOURCOUNT) IC_JOURCOUNT_CDD IC_JOURCOUNT

100	LINPUT "CYCLE COUNT JOURNAL NUMBER: "; BATCH_NO$

	%INCLUDE "SOURCE:[IC.OPEN]IC_JOURCOUNT.MOD"

110	LINPUT "LOCATION: "; LOCATION$
	LOCATION$ = LEFT(LOCATION$ + "    ", 4%)

120	LINPUT "REPORT FILE NAME: "; REPORT_NAME$

	CALL ASSG_CHANNEL(REPORT.CH%, STAT%)
	OPEN REPORT_NAME$ FOR INPUT AS FILE REPORT.CH%

1000	LINPUT #REPORT.CH%, RL$

	PRODUCT$ = LEFT(RL$, 14%)

	GOTO 1000 IF PRODUCT$ = ""

1100	WHEN ERROR IN
		GET #IC_JOURCOUNT.CH%, &
			KEY #0% EQ LOCATION$ + PRODUCT$
	USE
		CONTINUE 1000
	END WHEN

	DELETE #IC_JOURCOUNT.CH%
	PRINT PRODUCT$

	GOTO 1000

32767	END
