1	!
	!++
	! Description:
	!
	!	MERGE two IC_TRANSACTION master files together.
	!	BE CAREFUL THAT THIS IS WHAT YOU REALLY WANT TO DO
	!
	! History:
	!
	!	04/10/2002 - Kevin Handy
	!--

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[IC.OPEN]IC_TRANSACTION.HB"
	MAP (IC_TRANSACTION) IC_TRANSACTION_CDD IC_TRANSACTION

	LINPUT "Period (YYYYPP) "; YYYYPP$

100	!
	! Open up product master file
	!
	%INCLUDE "SOURCE:[IC.OPEN]IC_TRANSACTION.OPN"
	IC_TRANSACTION_PLAZA.CH% = IC_TRANSACTION.CH%
	RESET #IC_TRANSACTION_PLAZA.CH%
	IC_TRANSACTION.CH% = 0%

200	!
	! Open up other product file
	!
	IC_TRANSACTION.DEV$ = "$DISK2:[ROBSON]"
	%INCLUDE "SOURCE:[IC.OPEN]IC_TRANSACTION.MOD"
	IC_TRANSACTION_MARCO.CH% = IC_TRANSACTION.CH%
	IC_TRANSACTION.CH% = 0%

1000	!
	! Search for the next "O" category item
	!
	WHEN ERROR IN
		GET #IC_TRANSACTION_PLAZA.CH%, REGARDLESS
	USE
		CONTINUE 2000
	END WHEN

1010	WHEN ERROR IN
		PUT #IC_TRANSACTION_MARCO.CH%
	USE
		PRINT "FAILED: " + IC_TRANSACTION::PRODUCT
		CONTINUE 1900
	END WHEN

	PRINT "ADDED: " + &
		IC_TRANSACTION::PRODUCT + " " + &
		IC_TRANSACTION::TRANS_DATE

1900	GOTO 1000

2000	!

32767	END
