1	! Special program to sero out dollar column in the
	! chart periods
	!
	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[GL.OPEN]GL_CHART.HB"
	MAP (GL_CHART) GL_CHART_CDD GL_CHART

100	%INCLUDE "SOURCE:[GL.OPEN]GL_CHART.MOD"

1000	RESET #GL_CHART.CH%

1010	GET #GL_CHART.CH%

	GL_CHART::DOLLAR(I%) = 0.0 FOR I% = 0% TO 20%
	GL_CHART::UNIT(I%) = 0.0 FOR I% = 0% TO 20%
	GL_CHART::HOUR(I%) = 0.0 FOR I% = 0% TO 20%
	GL_CHART::RUNDOL = 0.0
	GL_CHART::RUNUNIT = 0.0
	GL_CHART::CURDOL = 0.0
	GL_CHART::CURUNIT = 0.0

	UPDATE #GL_CHART.CH%

	GOTO 1010

32767	END
