DEFINE RECORD CDD$TOP.TV.TV_COMMER_HEADER

        DESCRIPTION IS /*TV Commercial Header File*/.

        TV_COMMER_HEADER_CDD STRUCTURE.

        END TV_COMMER_HEADER_CDD STRUCTURE.

END TV_COMMER_HEADER.
