DEFINE RECORD CDD$TOP.TV.TV_COMMER_COMMENT

        DESCRIPTION IS /*TV Commercial Comments (Text Library)*/.

        TV_COMMER_COMMENT_CDD STRUCTURE.

        END TV_COMMER_COMMENT_CDD STRUCTURE.

END TV_COMMER_COMMENT.
