DEFINE RECORD CDD$TOP.TV.TV_LOG_COMMENT

        DESCRIPTION IS /*TV Comment Log (Store in a Text Library)*/.

        TV_LOG_COMMENT_CDD STRUCTURE.

        END TV_LOG_COMMENT_CDD STRUCTURE.

END TV_LOG_COMMENT.
