1	!
	! Fix DEAL_PRODUCT data file problem
	!
	! History
	!
	!	06/13/2002 - Kevin Handy
	!		Originasl version
	!


	%INCLUDE "SOURCE:[PC.OPEN]PC_DEAL_PRODUCT.HB"
	MAP (PC_DEAL_PRODUCT) PC_DEAL_PRODUCT_CDD PC_DEAL_PRODUCT

	!
	! OLD File Layout for: PC.PC_DEAL_PRODUCT on 03-Oct-01
	!
	! Products in a deal
	!
	RECORD PC_DEAL_PRODUCT_OLD_CDD
		! Element =
		! Description = Deal number
		STRING DEAL = 10
		! Element = PRODUCT
		! Description = Product Number
		STRING PRODUCT = 14
		! Element = AMOUNT
		! Description = Price in deal
		GFLOAT PRICE
		! Element = PERCENTAGE
		! Description = Percentage Discount
		GFLOAT PERCENT
		! Element = ACCOUNT
		! Description = General Ledger Account Number
		STRING ACCOUNT = 18
	END RECORD

	MAP (PC_DEAL_PRODUCT_OLD) PC_DEAL_PRODUCT_OLD_CDD PC_DEAL_PRODUCT_OLD


100	%INCLUDE "SOURCE:[PC.OPEN]PC_DEAL_PRODUCT.CRE"

110	!======================================================================
	! PC_DEAL_PRODUCT_OLD file (open read only)
	!======================================================================

	CALL ASSG_CHANNEL(PC_DEAL_PRODUCT_OLD.CH%, STAT%)

	PC_DEAL_PRODUCT_OLD.NAME$ = PC_DEAL_PRODUCT.DEV$ + "PC_DEAL_PRODUCT.MAS_OLD"

	OPEN PC_DEAL_PRODUCT_OLD.NAME$ FOR INPUT AS FILE PC_DEAL_PRODUCT_OLD.CH%, &
		ORGANIZATION INDEXED FIXED, &
		MAP PC_DEAL_PRODUCT_OLD, &
		PRIMARY KEY &
		( &
			PC_DEAL_PRODUCT_OLD::DEAL, &
			PC_DEAL_PRODUCT_OLD::PRODUCT &
		), &
		ALTERNATE KEY &
		( &
			PC_DEAL_PRODUCT_OLD::PRODUCT, &
			PC_DEAL_PRODUCT_OLD::DEAL &
		)	CHANGES, &
		ACCESS READ, ALLOW MODIFY

1000	RESET #PC_DEAL_PRODUCT_OLD.CH%

1100	WHEN ERROR IN
		GET #PC_DEAL_PRODUCT_OLD.CH%
	USE
		CONTINUE 1900
	END WHEN

	PC_DEAL_PRODUCT::DEAL = PC_DEAL_PRODUCT_OLD::DEAL
	PC_DEAL_PRODUCT::PRODUCT = PC_DEAL_PRODUCT_OLD::PRODUCT
	PC_DEAL_PRODUCT::PRICE = PC_DEAL_PRODUCT_OLD::PRICE
	PC_DEAL_PRODUCT::PERCENT = PC_DEAL_PRODUCT_OLD::PERCENT
	PC_DEAL_PRODUCT::ACCOUNT = PC_DEAL_PRODUCT_OLD::ACCOUNT

	PUT #PC_DEAL_PRODUCT.CH%

	PRINT PC_DEAL_PRODUCT::DEAL; " "; PC_DEAL_PRODUCT::PRODUCT

1800	GOTO 1100

1900	CLOSE #PC_DEAL_PRODUCT_OLD.CH%
	CLOSE #PC_DEAL_PRODUCT.CH%

32767	END
