DEFINE RECORD CDD$TOP.TK.TK_WORDINDEX

        DESCRIPTION IS /*Word Index - Used to Determine Docu Index*/.

        TK_WORDINDEX_CDD STRUCTURE.

        END TK_WORDINDEX_CDD STRUCTURE.

END TK_WORDINDEX.
