1	%TITLE "Register Maintenance"
	%SBTTL "MO_MAST_REGISTER"
	%IDENT "V3.6a Calico"

	!
	! COPYRIGHT (C) 1991 BY
	!
	! Computer Management Center
	! Idaho Falls, Idaho.
	!
	! This software is furnished under a license and may be used and
	! copied only in accordance with terms of such license and with
	! the inclusion of the above copyright notice.  This software or
	! any other copies thereof may not be provided or otherwise made
	! available to any other person.  No title to and ownership of
	! the software is hereby transferred.
	!
	! The information in this software is subject to change without
	! notice and should not be construed as a commitment by
	! Computer Management Center, Inc.
	!
	! CMC assumes no responsibility for the use or reliability of
	! its software on equipment which is not supported by CMC.
	!
	!++
	! Abstract:HELP
	!	.p
	!	The ^*Register Maintenance\* option
	!	maintains register entries for manufacturing orders.
	!
	! Index:
	!	.x Manufacturing Order Register
	!
	! Option:
	!
	!	OE_MAIN_REGHEADER$HELP
	!	MO_MAIN_REGLINE$HELP
	!	MO_MAIN_REGLINEOPT$HELP
	!	OE_MAIN_REGLINE$HELP
	!
	! Compile:
	!
	!	$ BAS MO_SOURCE:MO_MAST_REGISTER/LINE
	!	$ LINK/EXE=MO_EXE: MO_MAST_REGISTER, -
	!		FUNC_LIB:CMCLINK/OPTION
	!	$ DELETE MO_MAST_REGISTER.OBJ;*
	!
	! Author:
	!
	!	03/04/91 - Val James Allen
	!
	! Modification history:
	!
	!	10/27/29 - Dan Perkins
	!		Allow parts maintenance by adding OE_REGLINE code.
	!
	!	11/17/92 - Kevin Handy
	!		Clean up (Check)
	!
	!	03/31/93 - Dan Perkins
	!		Use OE_REGHEADER instead of MO_REGHEADER.
	!
	!	04/15/95 - Kevin Handy
	!		(V3.6)
	!		Update to V3.6 coding standards
	!
	!	08/19/98 - Kevin Handy
	!		(V3.6a Calico)
	!		Update to V3.6a coding standards
	!--
	%PAGE

	!
	! Set up compiling options
	!
	OPTION SIZE = (REAL GFLOAT, INTEGER LONG)

	%INCLUDE "FUNC_INCLUDE:FUNCTION.HB"

	MAP (SCOPE) SCOPE_STRUCT SCOPE

	%INCLUDE "FUNC_INCLUDE:MO_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:OE_WINDOW.INC"

	!
	! External functions
	!
	EXTERNAL LONG	FUNCTION MAIN_WINDOW
	EXTERNAL LONG	FUNCTION MAINT_GROUP

	%PAGE

	!*******************************************************************
	! Initilize maintainence
	!*******************************************************************

	CALL READ_INITIALIZE

1000	!*******************************************************************
	! Handle main program
	!*******************************************************************

	V% = MAIN_WINDOW(OE_MAIN_REGHEADER.ID, "")

	!******************************************************************
	! End of the program
	!******************************************************************

 ExitProgram:
	CALL SUBR_3EXITPROGRAM(SCOPE, "", "")

19000	!*******************************************************************
	! Trap errors
	!*******************************************************************

	FILENAME$ = ""

	RESUME HelpError

 HelpError:
	CALL HELP_34MESSAGE(SCOPE, NUM1$(ERL) + " " + ERT$(ERR), &
		"E", ERN$, FILENAME$, NUM1$(ERR))

	RESUME ExitProgram

19990	END


20000	FUNCTION LONG MAINT_GROUP(CDD_WINDOW_CDD SMG_WINDOW, LONG MOPTION, &
		LONG MLOOP, LONG MFLAG, STRING MVALUE)

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	!
	! Include files
	!
	%INCLUDE "FUNC_INCLUDE:FUNCTION.HB"

	MAP (SCOPE) SCOPE_STRUCT SCOPE

	%INCLUDE "FUNC_INCLUDE:MAIN_WINDOW.COM"
	%INCLUDE "FUNC_INCLUDE:AR_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:MO_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:OE_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:PD_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:SA_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:SB_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:UTL_WINDOW.INC"

	%INCLUDE "SOURCE:[CDD.OPEN]CDD_WINDOW.HB"

	%INCLUDE "SOURCE:[OE.OPEN]OE_REGHEADER.HB"
	MAP (OE_REGHEADER)	OE_REGHEADER_CDD	OE_REGHEADER
	MAP (OE_REGHEADER_OLD)	OE_REGHEADER_CDD	OE_REGHEADER_OLD
	MAP (OE_REGHEADER_ONE)	OE_REGHEADER_CDD	OE_REGHEADER_ONE

	%INCLUDE "SOURCE:[MO.OPEN]MO_REGLINE.HB"
	MAP (MO_REGLINE)	MO_REGLINE_CDD		MO_REGLINE
	MAP (MO_REGLINE_OLD)	MO_REGLINE_CDD		MO_REGLINE_OLD
	MAP (MO_REGLINE_ONE)	MO_REGLINE_CDD		MO_REGLINE_ONE

	!
	! External functions
	!
	EXTERNAL LONG FUNCTION MAIN_WINDOW
	EXTERNAL LONG FUNCTION AR_MAIN_35CUSTOM
	EXTERNAL LONG FUNCTION MO_MAIN_REGLINE
	EXTERNAL LONG FUNCTION MO_MAIN_REGLINEOPT
	EXTERNAL LONG FUNCTION MO_MAIN_MAKE
	EXTERNAL LONG FUNCTION MO_MAIN_MAKE_LINE
	EXTERNAL LONG FUNCTION MO_MAIN_MODEL
	EXTERNAL LONG FUNCTION MO_MAIN_MODEL_LINE
	EXTERNAL LONG FUNCTION MO_MAIN_MAKETYPE
	EXTERNAL LONG FUNCTION MO_MAIN_MAKESIZE
	EXTERNAL LONG FUNCTION MO_MAIN_MODELCODE
	EXTERNAL LONG FUNCTION MO_MAIN_OPTGROUP
	EXTERNAL LONG FUNCTION MO_MAIN_OPTION
	EXTERNAL LONG FUNCTION OE_MAIN_REGHEADER
	EXTERNAL LONG FUNCTION OE_MAIN_REGLINE
	EXTERNAL LONG FUNCTION OE_MAIN_ORDERTYPE
	EXTERNAL LONG FUNCTION OE_MAIN_SALESTAX
	EXTERNAL LONG FUNCTION OE_MAIN_SHIPTO
	EXTERNAL LONG FUNCTION OE_MAIN_CATEGORY
	EXTERNAL LONG FUNCTION PD_MAIN_PRODUCT
	EXTERNAL LONG FUNCTION SA_MAIN_SALESMAN
	EXTERNAL LONG FUNCTION SB_MAIN_SUBACCOUNT
	EXTERNAL LONG FUNCTION UT_MAIN_CARRIER
	EXTERNAL LONG FUNCTION UT_MAIN_TERMS
	EXTERNAL LONG FUNCTION UTL_MAIN_LOCATION
	EXTERNAL LONG FUNCTION UTL_MAIN_COUNTRY

	%PAGE

	SELECT SMG_WINDOW::IDENT

	CASE OE_MAIN_REGHEADER.ID

		MAINT_GROUP = OE_MAIN_REGHEADER(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

		SELECT MOPTION

		CASE OPT_ENTRY
			OE_REGHEADER_ONE = OE_REGHEADER

		CASE OPT_OPTLIST
			MVALUE = MVALUE + " line_manU Line "

		CASE OPT_MOREMENU
			OE_REGHEADER_ONE = OE_REGHEADER

			SELECT EDIT$(MVALUE, -1%)

			!
			! Line
			!
			CASE "LINE_MANU"
	!++
	! Abstract:LINE_MANU
	!--
				MAINT_GROUP = MAIN_WINDOW(MO_MAIN_REGLINE.ID, "")

			CASE "LINE"

	!++
	! Abstract:LINE
	!--

				MAINT_GROUP = MAIN_WINDOW(OE_MAIN_REGLINE.ID, "")

			END SELECT

		CASE OPT_AFTEROPT

			SELECT MVALUE

			!
			! Need to remove under old key, and insert under
			! (possibly) new key
			!
			CASE "Change", "Blank", "Initialize"
				IF OE_REGHEADER::ORDNUM <> &
					OE_REGHEADER_OLD::ORDNUM
				THEN
					OE_REGHEADER_ONE = OE_REGHEADER_OLD
					MAINT_GROUP = MAIN_WINDOW( &
						MO_MAIN_REGLINE.ID, "C")
				END IF

			!
			! Check for location change and if so then reset
			! inventory quantities from old location to new
			! location.
			!
				IF OE_REGHEADER::LOCATION <> OE_REGHEADER_OLD::LOCATION
				THEN
					OE_REGHEADER_ONE = OE_REGHEADER_OLD
					MAINT_GROUP = MAIN_WINDOW( &
						MO_MAIN_REGLINE.ID, "R")
				END IF

			!
			! Erase records in subwindow
			!
			CASE "Erase"
				OE_REGHEADER_ONE = OE_REGHEADER
				MAINT_GROUP = MAIN_WINDOW(MO_MAIN_REGLINE.ID, "E")

			END SELECT

		END SELECT

	CASE MO_MAIN_REGLINE.ID

		SELECT MOPTION

		CASE OPT_RESETDEFAULT
			MVALUE = OE_REGHEADER_ONE::ORDNUM

		CASE OPT_SUBWIND

			SELECT MLOOP

			CASE 6%
				MVALUE = OE_REGHEADER::ORDNUM

			CASE ELSE
				MVALUE = OE_REGHEADER_ONE::ORDNUM

			END SELECT

		CASE OPT_OPTLIST
			MVALUE = MVALUE + " Options "

		CASE OPT_MOREMENU
			MO_REGLINE_ONE = MO_REGLINE

			SELECT EDIT$(MVALUE, -1%)

			!
			! Options
			!
			CASE "OPTIONS"
	!++
	! Abstract:OPTIONS
	!--
				MAINT_GROUP = &
					MAIN_WINDOW(MO_MAIN_REGLINEOPT.ID, "")

			END SELECT

		CASE OPT_AFTEROPT

			SELECT MVALUE

			!
			! Need to remove under old key, and insert under
			! (possibly) new key
			!
			CASE "Change", "Blank", "Initialize"
				IF OE_REGHEADER::ORDNUM + MO_REGLINE::LIN <> &
					OE_REGHEADER_OLD::ORDNUM + MO_REGLINE_OLD::LIN
				THEN
					MO_REGLINE_ONE = MO_REGLINE_OLD
					MAINT_GROUP = MAIN_WINDOW( &
						MO_MAIN_REGLINEOPT.ID, "C")
				END IF

			!
			! Erase records in subwindow
			!
			CASE "Erase"
				MO_REGLINE_ONE = MO_REGLINE
				MAINT_GROUP = MAIN_WINDOW(MO_MAIN_REGLINEOPT.ID, "E")

			END SELECT

		END SELECT

		MAINT_GROUP = MO_MAIN_REGLINE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_REGLINEOPT.ID

		SELECT MOPTION

		CASE OPT_RESETDEFAULT
			MVALUE = MO_REGLINE_ONE::ORDNUM + MO_REGLINE_ONE::LIN

		CASE OPT_SUBWIND

			SELECT MLOOP

			CASE 6%
				MVALUE = MO_REGLINE::ORDNUM + MO_REGLINE::LIN

			CASE ELSE
				MVALUE = MO_REGLINE_ONE::ORDNUM + &
					MO_REGLINE_ONE::LIN

			END SELECT

		END SELECT

		MAINT_GROUP = MO_MAIN_REGLINEOPT(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_REGLINE.ID

		SELECT MOPTION

		CASE OPT_RESETDEFAULT
			MVALUE = OE_REGHEADER_ONE::ORDNUM

		CASE OPT_SUBWIND

			SELECT MLOOP

			CASE 6%
				MVALUE = OE_REGHEADER::ORDNUM

			CASE ELSE
				MVALUE = OE_REGHEADER_ONE::ORDNUM

			END SELECT

		END SELECT

		MAINT_GROUP = OE_MAIN_REGLINE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MAKE.ID

		MAINT_GROUP = MO_MAIN_MAKE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MAKE_LINE.ID

		MAINT_GROUP = MO_MAIN_MAKE_LINE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MODEL.ID

		MAINT_GROUP = MO_MAIN_MODEL(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MODEL_LINE.ID

		MAINT_GROUP = MO_MAIN_MODEL_LINE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MAKETYPE.ID

		MAINT_GROUP = MO_MAIN_MAKETYPE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MAKESIZE.ID

		MAINT_GROUP = MO_MAIN_MAKESIZE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MODELCODE.ID

		MAINT_GROUP = MO_MAIN_MODELCODE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_SHIPTO.ID

		MAINT_GROUP = OE_MAIN_SHIPTO(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_ORDERTYPE.ID

		MAINT_GROUP = OE_MAIN_ORDERTYPE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_SALESTAX.ID

		MAINT_GROUP = OE_MAIN_SALESTAX(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_CATEGORY.ID

		MAINT_GROUP = OE_MAIN_CATEGORY(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE AR_MAIN_35CUSTOM.ID

		MAINT_GROUP = AR_MAIN_35CUSTOM(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE UT_MAIN_CARRIER.ID

		MAINT_GROUP = UT_MAIN_CARRIER(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE UT_MAIN_TERMS.ID

		MAINT_GROUP = UT_MAIN_TERMS(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE UTL_MAIN_COUNTRY.ID

		MAINT_GROUP = UTL_MAIN_COUNTRY(SMG_WINDOW, &
			MOPTION, MLOOP, MFLAG, MVALUE)

	CASE UTL_MAIN_LOCATION.ID

		MAINT_GROUP = UTL_MAIN_LOCATION(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE SA_MAIN_SALESMAN.ID

		MAINT_GROUP = SA_MAIN_SALESMAN(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE SB_MAIN_SUBACCOUNT.ID

		MAINT_GROUP = SB_MAIN_SUBACCOUNT(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_OPTION.ID

		MAINT_GROUP = MO_MAIN_OPTION(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_OPTGROUP.ID

		MAINT_GROUP = MO_MAIN_OPTGROUP(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE PD_MAIN_PRODUCT.ID

		MAINT_GROUP = PD_MAIN_PRODUCT(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	END SELECT

32767	END FUNCTION
