1	%TITLE "Manufacturing Order Query"
	%SBTTL "MO_QURY_QUERY"
	%IDENT "V3.6a Calico"

	!
	! COPYRIGHT (C) 1991 BY
	!
	! Computer Management Center
	! Idaho Falls, Idaho.
	!
	! This software is furnished under a license and may be used and
	! copied only in accordance with terms of such license and with
	! the inclusion of the above copyright notice.  This software or
	! any other copies thereof may not be provided or otherwise made
	! available to any other person.  No title to and ownership of
	! the software is hereby transferred.
	!
	! The information in this software is subject to change without
	! notice and should not be construed as a commitment by
	! Computer Management Center, Inc.
	!
	! CMC assumes no responsibility for the use or reliability of
	! its software on equipment which is not supported by CMC.
	!
	!++
	! Abstract:HELP
	!	.b
	!	.lm +5
	!	The ^*Manufacturing Order Query\* option
	!	views Order Register Records on line.
	!	.lm -5
	!
	! Index:
	!	.x Manufacturing Order Query
	!
	! Option:
	!
	!	MO_MAIN_QUERY$HELP
	!	MO_MAIN_QUERYLINE$HELP
	!
	! Compile:
	!
	!	$ BAS MO_SOURCE:MO_QURY_QUERY/LINE
	!	$ LINK/EXE=MO_EXE: MO_QURY_QUERY, -
	!		FUNC_LIB:CMCLINK/OPTION
	!	$ DELETE MO_QURY_QUERY.OBJ;*
	!
	! Author:
	!
	!	03/04/91 - Val James Allen
	!
	! Modification history:
	!
	!	04/15/95 - Kevin Handy
	!		(V3.6)
	!		Update to V3.6 coding standards
	!
	!	07/10/96 - Kevin Handy
	!		Lose reference to MO_MAIN_REGHEADER, which
	!		was never called by anything.
	!		Reformat source code.
	!
	!	07/25/96 - Kevin Handy
	!		Reformat source code.
	!		Lose commented out code.
	!		Change references from MO_REGHEADER to
	!		OE_REGHEADER.
	!
	!	08/25/96 - Kevin Handy
	!		Clean up (Check)
	!
	!	08/19/98 - Kevin Handy
	!		(V3.6a Calico)
	!		Update to V3.6a coding standards
	!
	!	06/10/99 - Kevin Handy
	!		Lose HelpFile (Dead Code)
	!--
	%PAGE

	!
	! Set up compiling options
	!
	OPTION SIZE = (REAL GFLOAT, INTEGER LONG)

	%INCLUDE "FUNC_INCLUDE:FUNCTION.HB"

	MAP (SCOPE) SCOPE_STRUCT SCOPE

	%INCLUDE "FUNC_INCLUDE:MO_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:OE_WINDOW.INC"

	!
	! External functions
	!
	EXTERNAL LONG	FUNCTION MAIN_WINDOW
	EXTERNAL LONG	FUNCTION MAINT_GROUP

	%PAGE

	!*******************************************************************
	! Initilize maintainence
	!*******************************************************************

	CALL READ_INITIALIZE

1000	!*******************************************************************
	! Handle main program
	!*******************************************************************

	V% = MAIN_WINDOW(OE_MAIN_QUERYORDER.ID, "")

	!******************************************************************
	! End of the program
	!******************************************************************

 ExitProgram:
	CALL SUBR_3EXITPROGRAM(SCOPE, "", "")

19000	!*******************************************************************
	! Trap errors
	!*******************************************************************

	FILENAME$ = ""

	RESUME HelpError

 ! HelpFile:
 !	CALL HELP_34MESSAGE(SCOPE, NUM1$(ERL) + " " + ERT$(ERR), &
 !		"E", ERN$, FILENAME$, NUM1$(ERR))
 !	RESUME ExitProgram

 HelpError:
	CALL HELP_34MESSAGE(SCOPE, NUM1$(ERL) + " " + ERT$(ERR), &
		"E", ERN$, FILENAME$, NUM1$(ERR))
	RESUME ExitProgram

19990	END


20000	FUNCTION LONG MAINT_GROUP(CDD_WINDOW_CDD SMG_WINDOW, LONG MOPTION, &
		LONG MLOOP, LONG MFLAG, STRING MVALUE)

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	!
	! Include files
	!
	%INCLUDE "FUNC_INCLUDE:FUNCTION.HB"

	MAP (SCOPE) SCOPE_STRUCT SCOPE

	%INCLUDE "FUNC_INCLUDE:MAIN_WINDOW.COM"
	%INCLUDE "FUNC_INCLUDE:OE_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:MO_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:AR_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:UTL_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:PD_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:SA_WINDOW.INC"
	%INCLUDE "FUNC_INCLUDE:SB_WINDOW.INC"

	%INCLUDE "SOURCE:[CDD.OPEN]CDD_WINDOW.HB"

	%INCLUDE "SOURCE:[OE.OPEN]OE_REGHEADER.HB"
	MAP (OE_REGHEADER)	OE_REGHEADER_CDD	OE_REGHEADER
	MAP (OE_REGHEADER_OLD)	OE_REGHEADER_CDD	OE_REGHEADER_OLD
	MAP (OE_REGHEADER_ONE)	OE_REGHEADER_CDD	OE_REGHEADER_ONE

	%INCLUDE "SOURCE:[MO.OPEN]MO_REGLINE.HB"
	MAP (MO_REGLINE)	MO_REGLINE_CDD		MO_REGLINE
	MAP (MO_REGLINE_OLD)	MO_REGLINE_CDD		MO_REGLINE_OLD
	MAP (MO_REGLINE_ONE)	MO_REGLINE_CDD		MO_REGLINE_ONE

	!
	! External functions
	!
	EXTERNAL LONG FUNCTION OE_MAIN_QUERYORDER
	EXTERNAL LONG FUNCTION MO_MAIN_QUERYLINE
	EXTERNAL LONG FUNCTION MO_MAIN_REGLINEOPT
	EXTERNAL LONG FUNCTION OE_MAIN_ORDERTYPE
	EXTERNAL LONG FUNCTION OE_MAIN_SALESTAX
	EXTERNAL LONG FUNCTION OE_MAIN_SHIPTO
	EXTERNAL LONG FUNCTION OE_MAIN_CATEGORY
	EXTERNAL LONG FUNCTION AR_MAIN_35CUSTOM
	EXTERNAL LONG FUNCTION UT_MAIN_CARRIER
	EXTERNAL LONG FUNCTION UT_MAIN_TERMS
	EXTERNAL LONG FUNCTION UTL_MAIN_LOCATION
	EXTERNAL LONG FUNCTION UTL_MAIN_COUNTRY
	EXTERNAL LONG FUNCTION MAIN_WINDOW
	EXTERNAL LONG FUNCTION SA_MAIN_SALESMAN
	EXTERNAL LONG FUNCTION SB_MAIN_SUBACCOUNT
	EXTERNAL LONG FUNCTION MO_MAIN_MAKE
	EXTERNAL LONG FUNCTION MO_MAIN_MAKE_LINE
	EXTERNAL LONG FUNCTION MO_MAIN_MODEL
	EXTERNAL LONG FUNCTION MO_MAIN_MODEL_LINE
	EXTERNAL LONG FUNCTION MO_MAIN_MAKETYPE
	EXTERNAL LONG FUNCTION MO_MAIN_MAKESIZE
	EXTERNAL LONG FUNCTION MO_MAIN_MODELCODE
	EXTERNAL LONG FUNCTION MO_MAIN_OPTGROUP
	EXTERNAL LONG FUNCTION MO_MAIN_OPTION
	EXTERNAL LONG FUNCTION MO_MAIN_REGLINE

	%PAGE

	SELECT SMG_WINDOW::IDENT

	CASE OE_MAIN_QUERYORDER.ID

		MAINT_GROUP = OE_MAIN_QUERYORDER(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

		SELECT MOPTION
		CASE OPT_ENTRY
			OE_REGHEADER_ONE = OE_REGHEADER
		CASE OPT_OPTLIST
			MVALUE = MVALUE + " Line "
		CASE OPT_MOREMENU
			OE_REGHEADER_ONE = OE_REGHEADER

			SELECT EDIT$(MVALUE, -1%)
			!
			! Line
			!
			CASE "LINE"
	!++
	! Abstract:LINE
	!--
				MAINT_GROUP = &
					MAIN_WINDOW(MO_MAIN_QUERYLINE.ID, "")
			END SELECT
		END SELECT

	CASE MO_MAIN_QUERYLINE.ID

		SELECT MOPTION
		CASE OPT_RESETDEFAULT
			MVALUE = OE_REGHEADER_ONE::ORDNUM
		CASE OPT_SUBWIND
			SELECT MLOOP
			CASE 6%
				MVALUE = OE_REGHEADER::ORDNUM
			CASE ELSE
				MVALUE = OE_REGHEADER_ONE::ORDNUM
			END SELECT
		CASE OPT_OPTLIST
			MVALUE = "Find Next Restore Help View eXit Options"
		CASE OPT_MOREMENU
			MO_REGLINE_ONE = MO_REGLINE
			SELECT EDIT$(MVALUE, -1%)
			!
			! OPTIONS
			!
			CASE "OPTIONS"
	!++
	! Abstract:OPTIONS
	!--
				MAINT_GROUP = &
					MAIN_WINDOW(MO_MAIN_REGLINEOPT.ID, "V0")
			END SELECT

		END SELECT

		MAINT_GROUP = MO_MAIN_QUERYLINE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_REGLINEOPT.ID

		SELECT MOPTION
		CASE OPT_RESETDEFAULT
			MVALUE = MO_REGLINE_ONE::ORDNUM + MO_REGLINE_ONE::LIN
		CASE OPT_SUBWIND
			SELECT MLOOP
			CASE 6%
				MVALUE = MO_REGLINE::ORDNUM + MO_REGLINE::LIN
			CASE ELSE
				MVALUE = MO_REGLINE_ONE::ORDNUM + MO_REGLINE::LIN
			END SELECT

		END SELECT

		MAINT_GROUP = MO_MAIN_REGLINEOPT(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_REGLINE.ID

		MAINT_GROUP = MO_MAIN_REGLINE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MAKE.ID

		MAINT_GROUP = MO_MAIN_MAKE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MAKE_LINE.ID

		MAINT_GROUP = MO_MAIN_MAKE_LINE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MODEL.ID

		MAINT_GROUP = MO_MAIN_MODEL(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MODEL_LINE.ID

		MAINT_GROUP = MO_MAIN_MODEL_LINE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MAKETYPE.ID

		MAINT_GROUP = MO_MAIN_MAKETYPE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MAKESIZE.ID

		MAINT_GROUP = MO_MAIN_MAKESIZE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_MODELCODE.ID

		MAINT_GROUP = MO_MAIN_MODELCODE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_SHIPTO.ID

		MAINT_GROUP = OE_MAIN_SHIPTO(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_ORDERTYPE.ID

		MAINT_GROUP = OE_MAIN_ORDERTYPE(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_SALESTAX.ID

		MAINT_GROUP = OE_MAIN_SALESTAX(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE OE_MAIN_CATEGORY.ID

		MAINT_GROUP = OE_MAIN_CATEGORY(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE AR_MAIN_35CUSTOM.ID

		MAINT_GROUP = AR_MAIN_35CUSTOM(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE UT_MAIN_CARRIER.ID

		MAINT_GROUP = UT_MAIN_CARRIER(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE UT_MAIN_TERMS.ID

		MAINT_GROUP = UT_MAIN_TERMS(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE UTL_MAIN_LOCATION.ID

		MAINT_GROUP = UTL_MAIN_LOCATION(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE UTL_MAIN_COUNTRY.ID

		MAINT_GROUP = UTL_MAIN_COUNTRY(SMG_WINDOW, &
			MOPTION, MLOOP, MFLAG, MVALUE)

	CASE SA_MAIN_SALESMAN.ID

		MAINT_GROUP = SA_MAIN_SALESMAN(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE SB_MAIN_SUBACCOUNT.ID

		MAINT_GROUP = SB_MAIN_SUBACCOUNT(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_OPTION.ID

		MAINT_GROUP = MO_MAIN_OPTION(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	CASE MO_MAIN_OPTGROUP.ID

		MAINT_GROUP = MO_MAIN_OPTGROUP(SMG_WINDOW, MOPTION, &
			MLOOP, MFLAG, MVALUE)

	END SELECT

32767	END FUNCTION
