10	  ! &
	  ! Program name: opedes		Compiled with SCALE 0 on V09.3 &
	  ! Decompiled on 23-Dec-16 at 04:12 PM
50	  ON ERROR GOTO 19000 &
	\ DIM DEFAULT$(3%)
60	  OPEN "KB:" AS FILE 1%, MODE 8%+256% &
	\ CH%=1% &
	\ ESC$=CHR$(155%) &
	\ CLSCN$=ESC$+"[H"+ESC$+"[J" &
	\ CLRLIN$=ESC$+"[2K" &
	\ G.OFF$=ESC$+"[m" &
	\ B.ON$=ESC$+"[1m" &
	\ BLINK.ON$=ESC$+"[5m" &
	\ R.ON$=ESC$+"[7m" &
	\ COLM.ON$=ESC$+"[?3h" &
	\ COLM.OFF$=ESC$+"[?3l" &
	\ CLRBOT$=ESC$+"[21;1H"+ESC$+"[J" &
	\ LDS.ON$=ESC$+"(0" &
	\ USASCII$=ESC$+"(B"
80	  DROP.DEAD.DATE$="        " &
	\ VERSION.NO$="V1.0" &
	\ DATE.TIME$=SYS(CHR$(6%)+CHR$(20%)+CHR$(0%)+CHR$(0%)+CHR$(1%)+CHR$(SWAP%(1%))+STRING$(11%,0%)+CHR$(SWAP%(0%))+CHR$(1%)+CHR$(SWAP%(1%))) &
	\ IF DROP.DEAD.DATE$<>"" THEN  &
		  IF DROP.DEAD.DATE$<MID(SYS(DATE.TIME$),7%,8%) THEN  &
			  MESG$=MID(SYS(CHR$(6%)+CHR$(9%)+CHR$(47%)),3%,30%) &
			\ PRINT #CH%, MESG$; &
			\ V$=SYS(CHR$(9%))
100	  DEVICE.CH%=2% &
	\ OPEDES.CH%=2% &
	\ MENU.CH%=12% &
	\ LOOP.DATA%=3% &
	\ KEY.LEN%=64%
200	  IF FNO%(DEVICE.CH%,"DEVICE.DAT","/RO","")=0% THEN  &
		  OPEDES.DEVICE$=CVT$$(MID(FNL$,7%,20%),-1%) IF FNG%(DEVICE.CH%,"OPEDES")=0% &
		\ V%=FNC%(DEVICE.CH%)
300	  V%=FNO%(OPEDES.CH%,OPEDES.DEVICE$+"OPEDES.DAS","/RW/SF","") &
	\ V%=FNO%(OPEDES.CH%,OPEDES.DEVICE$+"OPEDES.DAS","/CR:"+NUM1$(KEY.LEN%)+","+"/SF","") IF FNS%=5% &
	\ IF FNS% THEN  &
		  V$=FNMESS$(CH%,FNS%,"OPEDES.DAS",0%,-1%) &
		\ OPT$="Q" &
		\ GOTO 1040
400	  OPEN "MENU.FIL/RO" FOR INPUT AS FILE MENU.CH% &
	\ DIM #12%, A0$(1%)=64% &
	\ COMPANY$=CVT$$(RIGHT(A0$(1%),2%),128%) &
	\ CLOSE MENU.CH%
450	  OPEN "NL:" AS FILE 11%, RECORDSIZE 64% &
	\ FIELD #11%, 6% AS OPEDES.OPERAT$,30% AS OPEDES.DESC$,6% AS OPEDES.DEPT$ &
	\ FIELD #11%, 64% AS OPEDES.BUF$
500	  FRAME$=FRAME$+FNP$(NUM1$(I%)+";1")+" "+FNP$(NUM1$(I%)+";80")+" " FOR I%=2% TO 19% &
	\ COMMAND$=" " &
	\ COMMAND$=COMMAND$+RIGHT(NUM1$(I%+100%),2%)+" " FOR I%=1% TO LOOP.DATA%
1000	  IF FNG%(OPEDES.CH%,"")=0% THEN  &
		  KEY.POINTER%=FNR(OPEDES.CH%) &
		\ GOTO 1010
1002	  PRINT #CH%, G.OFF$; &
	\ GOSUB 1060 &
	\ GOTO 1030
1005	  IF FNN%(OPEDES.CH%) THEN &
		  GOTO 18910 &
	  ELSE &
		  KEY.POINTER%=FNR(OPEDES.CH%) &
		\ GOTO 1015
1010	  PRINT #CH%, COLM.OFF$;FNSR$("1;24");G.OFF$; &
	\ GOSUB 1060
1015	  GOSUB 6000
1030	  CHNG.FLAG%=0% &
	\ PRINT #CH%, CLRBOT$;G.OFF$;"COMMAND: Add Erase Change Blank Initialize Default ";"Find Next Restore ";FNP$("22;10");"View Quit "; &
	\ OPT$=CVT$$(FNINP$(CH%,128%," ",1%,1%),32%) &
	\ OPT$="A" IF OPT$="" &
	\ GOTO 1030 IF KEY.POINTER%=0% AND INSTR(1%,"AQD",OPT$)=0%
1040	  IF OPT$="Q" THEN  &
		  PRINT #CH%, CLSCN$;FNSR$("1;24");FNP$("1;75");B.ON$;BLINK.ON$;R.ON$;"WAIT";G.OFF$;FNP$("24;1"); &
		\ V%=FNX%("",0%,"")
1050	  GOTO 1000 IF OPT$="R" &
	\ GOTO 1005 IF OPT$="N" &
	\ GOTO 2000 IF OPT$="A" OR OPT$="F" &
	\ GOTO 2200 IF OPT$="C" OR OPT$="B" &
	\ GOTO 2400 IF OPT$="E" &
	\ GOTO 2500 IF OPT$="D" &
	\ GOTO 2600 IF OPT$="I" &
	\ GOTO 4000 IF OPT$="V" &
	\ GOTO 1030
1060	  TEMP$="OPERATION DESCRIPTION FILE" &
	\ PRINT #CH%, COLM.OFF$;R.ON$;LEFT(TEMP$,39%);SPACE$(40%-LEN(TEMP$));SPACE$(40%-LEN(COMPANY$));COMPANY$;FRAME$;FNP$("20;1");SPACE$(80%);G.OFF$; &
	\ PRINT #CH%, FNP$("06;19");"(01) OPERATION CODE";FNP$("08;19");"(02) DESCRIPTION";FNP$("10;19");"(03) DEPARTMENT"; &
	\ RETURN
2000	  OPTION$="ADD " &
	\ OPTION$="FIND " IF OPT$="F" &
	\ INP$="" &
	\ FOR LOOP%=1% TO LOOP.DATA% &
		\ INP$=DEFAULT$(LOOP%) IF OPT$="A" &
		\ GOSUB 6030 &
	\ NEXT LOOP% &
	\ GOSUB 6210 &
	\ SEARCH.KEY$=OPEDES.OPERAT$+"" &
	\ IF OPT$="F" OR FNG%(OPEDES.CH%,SEARCH.KEY$)=0% THEN  &
		  KEY.POINTER%=FNR(OPEDES.CH%) &
		\ GOTO 1015
2100	  GOSUB 6010 FOR LOOP%=2% TO LOOP.DATA% &
	\ IF FNA%(OPEDES.CH%,OPEDES.BUF$) THEN  &
		  V$=FNMESS$(CH%,FNS%,"OPEDES.DAS",0%,-1%) &
		\ GOTO 1000
2110	  KEY.POINTER%=FNR(OPEDES.CH%) &
	\ GOTO 1030
2200	  IF OPT$="B" THEN &
		  OPTION$="BLANK " &
	  ELSE &
		  OPTION$="CHANGE " &
		\ CHNG.FLAG%=-1%
2210	  PRINT #CH%, CLRBOT$;OPTION$+":"; &
	\ INP$=CVT$$(FNINP$(CH%,128%," ",2%,1%),32%) &
	\ GOTO 1030 IF INP$="" &
	\ LOOP%=(INSTR(1%,COMMAND$," "+INP$+" ")+2%)/3% &
	\ GOTO 2210 IF LOOP%=0% AND OPT$="C" OR LOOP%<2% AND OPT$="B" &
	\ IF OPT$="C" THEN &
		  GOSUB 6010 &
	  ELSE &
		  INP$="" &
		\ GOSUB 6030
2220	  GOSUB 2900 &
	\ IF FNS%=0% THEN &
		  GOTO 2210 &
	  ELSE &
		  V$=FNMESS$(CH%,FNS%,"OPEDES.DAS",0%,-1%) &
		\ GOTO 1010
2400	  PRINT #CH%, CLRBOT$;"Confirm erasure (Yes/No) "; &
	\ INP$=CVT$$(FNINP$(CH%,128%," ",1%,1%),32%) &
	\ GOTO 1030 IF INP$<>"Y"
2420	  IF FND%(OPEDES.CH%,"") THEN &
		  V$=FNMESS$(CH%,FNS%,"OPEDES.DAS",0%,-1%) &
	  ELSE &
		  PRINT #CH%, FNP$("24;1");CLRLIN$;"Record has been erased.";FNP$("24;55");"Hit any key to continue "; &
		\ NW$=FNINP$(CH%,128%," ",1%,1%)
2430	  GOTO 1005
2500	  OPTION$="DEFAULT " &
	\ FOR LOOP%=1% TO LOOP.DATA% &
		\ INP$=DEFAULT$(LOOP%) &
		\ GOSUB 6030 &
	\ NEXT LOOP%
2510	  PRINT #CH%, CLRBOT$;"Default:"; &
	\ INP$=CVT$$(FNINP$(CH%,128%," ",2%,1%),32%) &
	\ GOTO 1010 IF INP$="" &
	\ LOOP%=(INSTR(1%,COMMAND$," "+INP$+" ")+2%)/3% &
	\ GOTO 2510 IF LOOP%<2% OR LOOP%>LOOP.DATA% &
	\ GOSUB 6010 &
	\ DEFAULT$(LOOP%)=INP$ &
	\ GOTO 2510
2600	  INITIALIZE$=" " &
	\ INP$="" &
	\ GOSUB 6030 FOR LOOP%=1% TO LOOP.DATA%
2610	  PRINT #CH%, CLRBOT$;FNP$("22;1");INITIALIZE$;FNP$("21;1");"Field to initialize:"; &
	\ INP$=CVT$$(FNINP$(CH%,128%," ",2%,1%),32%) &
	\ IF INP$<>"" THEN  &
		  LOOP%=(INSTR(1%,COMMAND$," "+INP$+" ")+2%)/3% &
		\ INITIALIZE$=INITIALIZE$+INP$+" " IF LOOP%<>0% AND (INSTR(1%,INITIALIZE$," "+INP$+" ")+2%)/3%=0% &
		\ GOTO 2610
2620	  GOTO 1010 IF INITIALIZE$="" &
	\ OPT$="C" &
	\ OPTION$="INITIALIZE " &
	\ CHNG.FLAG%=-1% &
	\ INP$="" &
	\ GOSUB 6030 FOR LOOP%=1% TO LOOP.DATA% &
	\ GOTO 2660
2650	  GOTO 18910 IF FNN%(OPEDES.CH%) &
	\ KEY.POINTER%=FNR(OPEDES.CH%)
2660	  GOSUB 6000 &
	\ FOR I%=1% TO LEN(INITIALIZE$)/3% &
		\ LOOP%=(INSTR(1%,COMMAND$,MID(INITIALIZE$,I%*3%-2%,3%))+2%)/3% &
		\ GOSUB 6010 &
		\ IF INP$<>"" THEN  &
			  GOSUB 2900 &
			\ IF FNS% THEN  &
				  V$=FNMESS$(CH%,FNS%,"OPEDES.DAS",0%,-1%) &
				\ GOTO 1010
2670			  NEXT I% &
	\ GOTO 2650
2900	  V%=FNG%(-OPEDES.CH%,NUM1$(KEY.POINTER%)) &
	\ V%=FNU%(-OPEDES.CH%,OPEDES.BUF$) IF FNS%=0% &
	\ RETURN
4000	  NAME.STRING$=" OPERATION DESCRIPTION"+SPACE$(20%)+"DEPARTMENT"+SPACE$(32%) &
	\ VIEW.USE$=" \    \    \"+SPACE$(28%)+"\ \        \" &
	\ LINE.POS$="001,011,042,080" &
	\ VIEW.LINES$="" &
	\ VIEW.LINES$=VIEW.LINES$+FNP$("19;"+MID(LINE.POS$,I%,3%))+R.ON$+LDS.ON$+CHR$(120%)+USASCII$ FOR I%=1% TO LEN(LINE.POS$) STEP 4% &
	\ PRINT #CH%, CLRBOT$;FNSR$("18;19");FNP$("19;1");R.ON$;NAME.STRING$;FNP$("20;1");SPACE$(80%);G.OFF$ &
	\ PRINTED.LINES%=0% &
	\ WINDOW%=1% &
	\ V%=FNG%(-OPEDES.CH%,NUM1$(KEY.POINTER%))
4010	  PRINT #CH%, RECORD 252%,CHR$(129%); &
	\ GET #CH%, RECORD 8192%
4020	  FIELD #CH%, RECOUNT AS TEST$ &
	\ GOTO 1010 IF INSTR(1%,TEST$,CHR$(3%))
4030	  LSET OPEDES.BUF$=FNL$+"" &
	\ PRINT #CH%, FNSR$(NUM1$(18%-PRINTED.LINES%)+";19"); IF WINDOW%=1% &
	\ PRINT #CH%, USING FNP$("19;1")+CHR$(10%)+VIEW.USE$+VIEW.LINES$+G.OFF$, OPEDES.OPERAT$,OPEDES.DESC$,OPEDES.DEPT$; &
	\ PRINTED.LINES%=PRINTED.LINES%+1% &
	\ GOTO 18910 IF FNN%(OPEDES.CH%) &
	\ IF PRINTED.LINES%>=17% THEN  &
		  PRINT #CH%, FNSR$("3;19") &
		\ V$=FNMESS$(CH%,0%,"",-1%,-1%) &
		\ WINDOW%,PRINTED.LINES%=0%
4040	  GOTO 4010
6000	  RETURN IF FNG%(-OPEDES.CH%,NUM1$(KEY.POINTER%)) &
	\ LSET OPEDES.BUF$=FNL$+"" &
	\ ON LOOP% GOSUB 6220,6240,6260 FOR LOOP%=1% TO LOOP.DATA% &
	\ RETURN
6010	  ON LOOP% GOSUB 6210,6230,6250 &
	\ RETURN
6030	  ON LOOP% GOSUB 6217,6237,6257 &
	\ RETURN
6200	  !
6210	  INP$=FNSIO$("","6;40",OPEDES.OPERAT$,DEFAULT$(LOOP%),CHR$(CH%)+STRING$(2%,LEN(OPEDES.OPERAT$))+CHR$(1%)+CHR$(0%)+OPTION$+" ALPHA") &
	\ GOTO 6210 IF INP$="" AND OPT$="A" &
	\ IF OPT$="C" OR OPT$="I" AND INP$<>"" THEN  &
		  IF FNG%(OPEDES.CH%,INP$+SPACE$(6%-LEN(INP$)))=0% THEN  &
			  PRINT #CH%, CLRBOT$;FNP$("24;1");"Duplicate key ";INP$;FNP$("21;1");"COMMAND: Re-enter Exit "; &
			\ IF FNINP$(CH%,128%," ",1%,0%)="R" THEN &
				  GOTO 6210 &
			  ELSE &
				  GOTO 6220
6217	  LSET OPEDES.OPERAT$=INP$ IF INP$<>"" OR CHNG.FLAG%=0%
6220	  PRINT #CH%, FNP$("6;40");B.ON$;OPEDES.OPERAT$;G.OFF$; &
	\ RETURN
6230	  INP$=FNSIO$("","8;40",OPEDES.DESC$,DEFAULT$(LOOP%),CHR$(CH%)+STRING$(2%,LEN(OPEDES.DESC$))+CHR$(1%)+CHR$(0%)+OPTION$+" ALPHA")
6237	  LSET OPEDES.DESC$=INP$ IF INP$<>"" OR CHNG.FLAG%=0%
6240	  PRINT #CH%, FNP$("8;40");B.ON$;OPEDES.DESC$;G.OFF$; &
	\ RETURN
6250	  INP$=FNSIO$("","10;40",OPEDES.DEPT$,DEFAULT$(LOOP%),CHR$(CH%)+STRING$(2%,LEN(OPEDES.DEPT$))+CHR$(1%)+CHR$(0%)+OPTION$+" ALPHA")
6257	  LSET OPEDES.DEPT$=INP$ IF INP$<>"" OR CHNG.FLAG%=0%
6260	  PRINT #CH%, FNP$("10;40");B.ON$;OPEDES.DEPT$;G.OFF$; &
	\ RETURN
18910	  PRINT #CH%, CLRBOT$;FNP$("24;1");"End of file has been reached.";FNP$("24;55");"Hit any key to continue "; &
	\ INP$=FNINP$(CH%,128%," ",1%,0%) &
	\ GOTO 1010 IF OPT$="V" &
	\ GOTO 1000
19000	  RESUME  IF ERR=52% OR ERR=51% &
	\ RESUME 450 IF ERL=400% &
	\ RESUME 4030 IF ERL=4010% &
	\ RESUME 1010 IF ERR=54%
19999	  ON ERROR GOTO 0
30000	  DEF FNINP$(CHN%,KYP%,FILLCHAR$,INPUTLEN%,TO.ERR%) &
	\ PRINT #CHN%, STRING$(INPUTLEN%,ASCII(FILLCHAR$));STRING$(INPUTLEN%,8%); &
	\ PRINT #CHN%, RECORD 256%,CHR$(KYP%+INPUTLEN%)+FILLCHAR$; &
	\ GET #CHN% &
	\ FIELD #CHN%, RECOUNT AS BUFFER$ &
	\ BUFFER$="%^C" IF INSTR(1%,BUFFER$,CHR$(3%)) &
	\ FNINP$=CVT$$(BUFFER$,4%) &
	\ V=SQR(-1.) IF BUFFER$="%^C" AND TO.ERR% &
	\ FNEND
30200	  DEF FNP$(ROWCOL$) &
	\ FNP$=ESC$+"["+ROWCOL$+"H" &
	\ FNEND
30250	  DEF FNMESS$(CHN%,ERRNUM%,DESC$,TO.ERR%,PRINT.TEST%) &
	\ MESG$=MID(SYS(CHR$(6%)+CHR$(9%)+CHR$(ERRNUM%)),3%,30%)+" "+DESC$ &
	\ MESG$=DESC$+"" IF ERRNUM%<1% &
	\ IF PRINT.TEST% THEN  &
		  PRINT #CHN%, FNP$("24;1");CLRLIN$;MESG$;FNP$("24;55");"Hit any key to continue."; &
		\ NW$=FNINP$(CHN%,128%," ",1%,TO.ERR%)
30260	  FNMESS$=MESG$ &
	\ FNEND
30280	  DEF FNSR$(BEGEND$) &
	\ FNSR$=ESC$+"["+BEGEND$+"r" &
	\ FNEND
30700	  DEF FNSIO$(FRMAT$,ROWCOL$,VARABLE$,DEFAL$,ITEMS$) &
	\ CHN%=ASCII(MID(ITEMS$,1%,1%)) &
	\ KIND%=ASCII(MID(ITEMS$,4%,1%)) &
	\ DECI=ASCII(MID(ITEMS$,5%,1%)) &
	\ OPT$=MID(ITEMS$,6%,1%)
30705	  PRINT #CHN%, FNP$(ROWCOL$);R.ON$;B.ON$; &
	\ IF OPT$="C" THEN &
		  ON KIND% GOTO 30710,30715,30720,30725,30730 &
	  ELSE &
		  PRINT #CHN%, SPACE$(ASCII(MID(ITEMS$,2%,1%))); &
		\ GOTO 30735
30710	  PRINT #CHN%, VARABLE$; &
	\ GOTO 30735
30715	  PRINT #CHN%, USING FRMAT$, ASCII(VARABLE$); &
	\ GOTO 30735
30720	  PRINT #CHN%, USING FRMAT$, CVT$%(VARABLE$)/10.^DECI; &
	\ GOTO 30735
30725	  PRINT #CHN%, FND6$(CVT$%(VARABLE$)); &
	\ GOTO 30735
30730	  PRINT #CHN%, USING FRMAT$, CVT$F(VARABLE$);
30735	  PRINT #CHN%, G.OFF$;CLRBOT$;RIGHT(ITEMS$,6%)+":  ";B.ON$; &
	\ FIN$=FNINP$(CHN%,0%,"_",ASCII(MID(ITEMS$,3%,1%)),1%) &
	\ V%=VAL(FIN$) IF KIND%=3% &
	\ V=VAL(FIN$) IF KIND%>3% &
	\ IF FIN$="" THEN  &
		  FIN$=DEFAL$ IF INSTR(1%,"CF",OPT$)=0% &
		\ GOTO 30745
30740	  IF KIND%=3% OR KIND%=5% THEN  &
		  TEMP=1. &
		\ TEMP=10.^DECI IF INSTR(1%,FIN$,".")=0% &
		\ FIN$=NUM1$(VAL(FIN$)/TEMP) &
		\ FIN$=FIN$+"." IF INSTR(1%,FIN$,".")=0%
30745	  FNSIO$=FIN$+"" &
	\ FNEND
32767	  END
