	!=======================================================================
	! 7400-7499	BA * Billing Agency System
	! This include file is used to DECLARE window numbers for BA system
	!=======================================================================

	DECLARE LONG CONSTANT BA_MAIN_BILTBL.ID			= 7400%
	DECLARE LONG CONSTANT BA_MAIN_CONTROL.ID		= 7410%
	DECLARE LONG CONSTANT BA_MAIN_CUSTOM.ID			= 7420%
	DECLARE LONG CONSTANT BA_MAIN_CUSTYP.ID			= 7430%
	DECLARE LONG CONSTANT BA_MAIN_JOURNAL.ID		= 7440%
	DECLARE LONG CONSTANT BA_MAIN_JOURNALL.ID		= 7450%

