	!=======================================================================
	! 7900-7999	BC * Customer Billing System
	! This include file is used to DECLARE window numbers for BC system
	!=======================================================================

	DECLARE LONG CONSTANT BC_MAIN_BILL.ID			= 7900%
	DECLARE LONG CONSTANT BC_MAIN_BILL_LINE.ID		= 7910%
	DECLARE LONG CONSTANT BC_MAIN_CONTROL.ID		= 7920%
	DECLARE LONG CONSTANT BC_MAIN_CUSTOM.ID			= 7930%
	DECLARE LONG CONSTANT BC_MAIN_CUSTYP.ID			= 7940%
