	!=======================================================================
	! 8700-8799	BM * Bill of Materials System
	! This include file is used to DECLARE window numbers for BM system
	!=======================================================================

	DECLARE LONG CONSTANT BM_MAIN_STRUCTURE.ID		= 8700%
	DECLARE LONG CONSTANT BM_MAIN_STRUCTURESCAN.ID		= 8710%
	DECLARE LONG CONSTANT BM_MAIN_PRODOPER.ID		= 8720%
	DECLARE LONG CONSTANT BM_MAIN_CONTROL.ID		= 8730%
	DECLARE LONG CONSTANT BM_MAIN_MAXMIN.ID			= 8740%
