	!=======================================================================
	! 3400-3499	AR * Accounts Recivable System
	! This include file is used to DECLARE window numbers for AR system
	!=======================================================================

	DECLARE LONG CONSTANT BR_MAIN_CUSTOM.ID			= 3400%
	DECLARE LONG CONSTANT BR_MAIN_CONTROL.ID		= 3401%
	DECLARE LONG CONSTANT BR_MAIN_BILL.ID			= 3402%
	DECLARE LONG CONSTANT BR_MAIN_BILL_LINE.ID		= 3403%

