	!=======================================================================
	! 4800-4899	BS * Billing for Services System
	! This include file is used to DECLARE window numbers for BS system
	!=======================================================================

	DECLARE LONG CONSTANT BS_MAIN_JOB.ID			= 4800%
	DECLARE LONG CONSTANT BS_MAIN_CONTROL.ID		= 4810%
	DECLARE LONG CONSTANT BS_MAIN_BILL.ID		        = 4815%
	DECLARE LONG CONSTANT BS_MAIN_PROGRAM.ID		= 4825%
	DECLARE LONG CONSTANT BS_MAIN_RATE.ID		        = 4830%
	DECLARE LONG CONSTANT BS_MAIN_CLIENT.ID		        = 4835%

