	!=======================================================================
	! 7300-7399	BT * Billing Tuition System
	! This include file is used to DECLARE window numbers for Bt system
	!=======================================================================

	DECLARE LONG CONSTANT BT_MAIN_CONTROL.ID		= 7310%
	DECLARE string CONSTANT BT_MAIN_CUSTOM.ID		= "7320%BAD"
	DECLARE LONG CONSTANT BT_MAIN_TUITION.ID		= 7330%
	DECLARE LONG CONSTANT BT_MAIN_CUSTYP.ID			= 7350%
	DECLARE LONG CONSTANT BT_MAIN_JOURNAL.ID		= 7360%
	DECLARE LONG CONSTANT BT_MAIN_JOURNALL.ID		= 7370%

