	!=======================================================================
	!  500- 599	CD * Compact Disc filing System
	! This include file is used to DECLARE window numbers for cd system
	!=======================================================================

	DECLARE LONG CONSTANT CD_MAIN_DISC.ID			= 505%
	DECLARE LONG CONSTANT CD_MAIN_TYPE.ID			= 525%
	DECLARE LONG CONSTANT CD_MAIN_LOOK.ID			= 545%
	DECLARE LONG CONSTANT CD_MAIN_SONG.ID			= 565%
