	!=======================================================================
	! 6500-6599	CK * Check Reconsiliation System
	! This include file is used to DECLARE window numbers for CK system
	!=======================================================================

	DECLARE LONG CONSTANT CK_MAIN_CKMNT.ID                  = 6510%
	DECLARE LONG CONSTANT CK_MAIN_CONTROL.ID                = 6520%
	DECLARE LONG CONSTANT CK_MAIN_CONTROLACC.ID             = 6530%
	DECLARE LONG CONSTANT CK_MAIN_MANUAL_CANCEL.ID          = 6540%
