	!=======================================================================
	! 7200-7299	CM * Conflict Managemant System
	! This include file is used to DECLARE window numbers for CM system
	!=======================================================================
	DECLARE LONG CONSTANT CM_MAIN_CONFLICT.ID		= 7210%
	DECLARE LONG CONSTANT CM_MAIN_CONFMATTER.ID		= 7215%
	DECLARE LONG CONSTANT CM_MAIN_CLIENT.ID			= 7220%
	DECLARE LONG CONSTANT CM_MAIN_QUERY.ID			= 7225%
	DECLARE LONG CONSTANT CM_MAIN_RELATION.ID		= 7230%
	DECLARE LONG CONSTANT CM_MAIN_RELTYPE.ID		= 7235%
