
	%NOLIST
	%NOCROSS

	!++
	! History:
	!	12/19/97 - Kevin Handy
	!		Reformat so it fit in 80 columns.
	!--

	!=================================================================
	DECLARE LONG CONSTANT CMC$_ABORT              =         10
	DECLARE LONG CONSTANT CMC$_DATEOUT            =         11
	DECLARE LONG CONSTANT CMC$_LEFT               =          0
	DECLARE LONG CONSTANT CMC$_MACRO              =         19
	DECLARE LONG CONSTANT CMC$_NOOPTION           =          4
	DECLARE LONG CONSTANT CMC$_NORMAL             =          1
	DECLARE LONG CONSTANT CMC$_RIGHT              =          1
	DECLARE LONG CONSTANT CMC$_TERMINATED         =          8
	DECLARE LONG CONSTANT CMC$_UNDEFINED          =          3
	DECLARE LONG CONSTANT CMC$_UNTERROR           =          2
	DECLARE LONG CONSTANT CMC$_WARNING            =          0
	!=================================================================
	DECLARE LONG CONSTANT OPT_ABORT               =          1
	DECLARE LONG CONSTANT OPT_ADDREC              =          2
	DECLARE LONG CONSTANT OPT_ASSIGN              =          3
	DECLARE LONG CONSTANT OPT_CHECK               =          4
	DECLARE LONG CONSTANT OPT_CLOSEFILE           =          5
	DECLARE LONG CONSTANT OPT_COMPLETE            =          6
	DECLARE LONG CONSTANT OPT_CONFIRM             =          7
	DECLARE LONG CONSTANT OPT_HHMMSS              =          0
	DECLARE LONG CONSTANT OPT_INTERRUPT           =          8
	DECLARE LONG CONSTANT OPT_MARKFILE            =          9
	DECLARE LONG CONSTANT OPT_MMDDYY              =          0
	DECLARE LONG CONSTANT OPT_OPENFILE            =         10
	DECLARE LONG CONSTANT OPT_POSTFILE            =         11
	DECLARE LONG CONSTANT OPT_REPORT              =         14
	DECLARE LONG CONSTANT OPT_RESTART             =         12
	DECLARE LONG CONSTANT OPT_SUMMARY             =         13
	!=================================================================
	DECLARE LONG CONSTANT SUBOPT_CHECK            =      65536
	DECLARE LONG CONSTANT SUBOPT_DETAIL           =     131072
	DECLARE LONG CONSTANT SUBOPT_FINAL            =     262144
	DECLARE LONG CONSTANT SUBOPT_LEDGER           =          1
	DECLARE LONG CONSTANT SUBOPT_LINEITEM         =          2
	DECLARE LONG CONSTANT SUBOPT_NOOPT            =          0
	DECLARE LONG CONSTANT SUBOPT_REGISTER         =          3
	DECLARE LONG CONSTANT SUBOPT_REVERSE          =     524288

	%LIST
	%CROSS
