	!=======================================================================
	! 6000-6099	EL * Equipment Ledger System
	! This include file is used to DECLARE window numbers for EL system
	!=======================================================================

	DECLARE LONG CONSTANT EL_MAIN_CONTROL.ID		= 6000%
	DECLARE LONG CONSTANT EL_MAIN_ACCOUNT.ID	        = 6010%
	DECLARE LONG CONSTANT EL_MAIN_EQUIPMENT.ID		= 6020%
	DECLARE LONG CONSTANT EL_MAIN_BALANCE.ID		= 6030%
	DECLARE LONG CONSTANT EL_MAIN_CLASS.ID	        	= 6040%
	DECLARE LONG CONSTANT EL_MAIN_TYPE.ID	        	= 6050%
	
