/*
 *++
 *******************************************************************
 * FUNCTION.H - Defines information necessary for proper
 * compilation of accounting programs
 *
 * Version 3.6
 *
 * This file is closely related to SCOPEDEF.COM and must be
 * changed at the same time.
 ********************************************************************
 *
 * Modification History:
 *
 *	11/11/97 - Kevin Handy
 *		Initial version with very little implemented
 *--
 */

#if 0
	!
	! CMC$ Codes
	!
	%INCLUDE "FUNC_INCLUDE:CONSTANTS.INC"
#endif

/*
 * Here are some some codes for the various OUTP types
 */
#define OUTP_TODISPLAY		1
#define OUTP_TOSPOOL		2
#define OUTP_TODEVICE		3
#define OUTP_TOFILE		4
#define OUTP_TOLOCAL		5
#define OUTP_TOWP		7
#define OUTP_TODOCUMENT		9
#define OUTP_TO2020		10
#define OUTP_TOPL		11

#if 0
	!
	! Scope definition
	!
	%INCLUDE "FUNC_INCLUDE:SCOPEDEF.COM"

	!
	! Function definitions for Software Solutions programs
	!
	! Always include complete definition of parameters for
	! better error detection.
	!
	EXTERNAL STRING FUNCTION ASSG_MAKEBATCH(STRING, STRING)
	EXTERNAL LONG	FUNCTION COMP_ARRAY(STRING, STRING)
	EXTERNAL LONG	FUNCTION COMP_STRING(STRING, STRING)
	EXTERNAL STRING	FUNCTION CONV_STRING(STRING, LONG)
	EXTERNAL LONG	FUNCTION COPY_COPYRECORDS(STRING, STRING)
	EXTERNAL STRING FUNCTION DATE_3SELECT(SCOPE_STRUCT, STRING)
	EXTERNAL LONG	FUNCTION DATE_DAYCODE(STRING)
	EXTERNAL LONG	FUNCTION DATE_DAYOFWEEK(LONG)
	EXTERNAL STRING FUNCTION DATE_DUEDATE(STRING, LONG, STRING)
	EXTERNAL STRING	FUNCTION DATE_INVDCODE(LONG)
	EXTERNAL STRING	FUNCTION DATE_INVMCODE(LONG)
	EXTERNAL LONG	FUNCTION DATE_MONCODE(STRING)
	EXTERNAL STRING	FUNCTION DATE_STOREDATE(STRING)
	EXTERNAL STRING	FUNCTION DATE_TODAY()
	EXTERNAL LONG	FUNCTION ENTR_3CHOICE(SCOPE_STRUCT, STRING, &
		STRING, STRING DIM (), STRING, LONG, STRING, &
		STRING, LONG)
	EXTERNAL STRING	FUNCTION ENTR_3DATE(SCOPE_STRUCT, LONG, &
		STRING, STRING, STRING, LONG, STRING, STRING)
	EXTERNAL LONG	FUNCTION ENTR_3ENTER(SCOPE_STRUCT, LONG, &
		LONG, LONG, STRING, LONG, LONG)
	EXTERNAL REAL	FUNCTION ENTR_3NUMBER(SCOPE_STRUCT, LONG, &
		STRING, STRING, REAL, LONG, STRING, STRING)
	EXTERNAL STRING	FUNCTION ENTR_3OPTION(SCOPE_STRUCT, STRING, &
		STRING, LONG, LONG)
	EXTERNAL STRING FUNCTION ENTR_3PHONE(SCOPE_STRUCT, LONG, &
		STRING, STRING, STRING, LONG, LONG, STRING)
	EXTERNAL STRING FUNCTION ENTR_3PRODUCT(SCOPE_STRUCT, LONG, &
		STRING, STRING, STRING, LONG, STRING, STRING)
	EXTERNAL STRING FUNCTION ENTR_3SSN(SCOPE_STRUCT, LONG, &
		STRING, STRING, STRING, LONG, STRING, STRING)
	EXTERNAL STRING	FUNCTION ENTR_3STRING(SCOPE_STRUCT, LONG, &
		STRING, STRING, STRING, LONG, STRING, STRING)
	EXTERNAL STRING	FUNCTION ENTR_3STRINGLIST(SCOPE_STRUCT, &
		LONG, STRING, STRING, STRING, LONG, &
		STRING, STRING, STRING DIM (), STRING, STRING)
	EXTERNAL STRING FUNCTION ENTR_3TIME(SCOPE_STRUCT, &
		LONG, STRING, STRING, STRING, LONG, STRING, STRING)
	EXTERNAL STRING	FUNCTION ENTR_3YESNO(SCOPE_STRUCT, LONG, &
		STRING, STRING, STRING, LONG, STRING, STRING)
	EXTERNAL LONG   FUNCTION ENTR_4ENTRY(SCOPE_STRUCT, &
		LONG by value, LONG by value)
	EXTERNAL LONG	FUNCTION ENTR_4SPECIALKEYS(SCOPE_STRUCT, LONG by value, &
		LONG by value, LONG by value)
	EXTERNAL STRING FUNCTION ENTR_BIT(LONG, STRING, &
		STRING, STRING, LONG, STRING, STRING, STRING, LONG, LONG)
	EXTERNAL STRING FUNCTION ENTR_DATUM(LONG, STRING, &
		STRING, STRING, LONG, STRING, STRING)
	EXTERNAL LONG   FUNCTION ENTR_MACRO(SCOPE_STRUCT)
	EXTERNAL STRING	FUNCTION ENTR_NOTE(LONG, &
		STRING, STRING, STRING, LONG, STRING, STRING)
	EXTERNAL STRING	FUNCTION ENTR_PERIOD(LONG, STRING, &
		STRING, STRING, LONG, STRING, STRING)
	EXTERNAL LONG	FUNCTION FIND_FILEEXISTS(STRING, LONG)
	EXTERNAL LONG	FUNCTION FUNC_BANNERCODE(STRING)
	EXTERNAL STRING FUNCTION FUNC_BITSTRING(LONG, STRING, LONG, STRING)
	EXTERNAL STRING FUNCTION FUNC_BITSWITCH(LONG, STRING, LONG)
	EXTERNAL LONG	FUNCTION FUNC_INCREMENT(STRING)
	EXTERNAL LONG   FUNCTION FUNC_MCLCOMMAND(SCOPE_STRUCT, &
		STRING DIM (), LONG, STRING, STRING)
	EXTERNAL LONG	FUNCTION FUNC_MODULUS(LONG, LONG)
	EXTERNAL LONG	FUNCTION FUNC_NUMBERADD(STRING, LONG)
	EXTERNAL STRING FUNCTION FUNC_REFORMAT(REAL, LONG, LONG)
	EXTERNAL REAL	FUNCTION FUNC_ROUND(REAL, LONG)
	EXTERNAL LONG	FUNCTION LIBR_3INSERT(STRING, STRING, STRING)
	EXTERNAL LONG   FUNCTION LIBR_CONNECT(STRING, STRING, STRING)
	EXTERNAL LONG	FUNCTION LIBR_DELETE(STRING, STRING)
	EXTERNAL LONG   FUNCTION LIBR_DIGSR(STRING, STRING, STRING DIM ())
	EXTERNAL LONG   FUNCTION LIBR_EDIT(STRING, STRING)
	EXTERNAL LONG	FUNCTION LIBR_EXTRACT(STRING, STRING, STRING)
	EXTERNAL LONG   FUNCTION LIBR_EXTRACTFILE(STRING, LONG, STRING, LONG)
	EXTERNAL LONG	FUNCTION LIBR_EXTRACTVAR(STRING, STRING, STRING)
	EXTERNAL LONG	FUNCTION LIBR_INSERTTEXT(STRING, STRING, STRING)
	EXTERNAL LONG   FUNCTION LIBR_INSERTVAR(STRING, STRING, STRING)
	EXTERNAL LONG	FUNCTION LIBR_MAINT(STRING, STRING, STRING, LONG)
	EXTERNAL LONG	FUNCTION LIBR_MAINTNODSR(STRING, STRING, STRING, LONG)
	EXTERNAL LONG   FUNCTION LIBR_NODIGSR(STRING, STRING, STRING DIM ())
	EXTERNAL STRING FUNCTION LIBR_SELECT(STRING, STRING, STRING, STRING)
	EXTERNAL LONG	FUNCTION MAIN_FAKEHEADER(LONG, STRING)
	EXTERNAL LONG	FUNCTION MAIN_JOURNAL(LONG, STRING)
	EXTERNAL LONG	FUNCTION MAIN_WINDOW(LONG, STRING)
	EXTERNAL STRING FUNCTION OUTP_CREATESTR(STRING, STRING)
	EXTERNAL STRING FUNCTION PRNT_CHECKPROTECT(REAL)
	EXTERNAL STRING	FUNCTION PRNT_DATE(STRING, LONG)
	EXTERNAL STRING FUNCTION PRNT_DATUM(STRING, LONG)
	EXTERNAL STRING FUNCTION PRNT_FANCYDATE(STRING)
	EXTERNAL STRING FUNCTION PRNT_MONTHYYYY(STRING)
	EXTERNAL STRING FUNCTION PRNT_NUMBERITH(LONG)
	EXTERNAL STRING FUNCTION PRNT_NUMBERTEXT(LONG)
	EXTERNAL STRING	FUNCTION PRNT_PHONE(STRING, LONG)
	EXTERNAL STRING	FUNCTION PRNT_SSN(STRING, LONG)
	EXTERNAL STRING	FUNCTION PRNT_TIME(STRING, LONG)
	EXTERNAL LONG	FUNCTION READ_BIT(LONG, STRING, LONG)
	EXTERNAL STRING	FUNCTION READ_DEFAULT()
	EXTERNAL LONG	FUNCTION READ_OWNERPID(LONG)
	EXTERNAL LONG	FUNCTION READ_PERIOD(STRING, STRING, STRING, &
		STRING, STRING, STRING, STRING, LONG)
	EXTERNAL LONG	FUNCTION READ_SYSDETACH()
	EXTERNAL STRING FUNCTION READ_SYSJOB()
	EXTERNAL STRING FUNCTION READ_SYSLOG(STRING)
	EXTERNAL STRING FUNCTION READ_SYSPID()
	EXTERNAL STRING FUNCTION READ_SYSPN()
	EXTERNAL STRING FUNCTION READ_USERNAME()
	EXTERNAL STRING FUNCTION TIME_ADD(STRING, STRING, STRING)
	EXTERNAL LONG	FUNCTION TIME_CODE(STRING)
	EXTERNAL STRING FUNCTION TIME_INVCODE(LONG)
	EXTERNAL STRING	FUNCTION TIME_NOW()
	EXTERNAL STRING FUNCTION TIME_STORETIME(STRING, STRING)
	EXTERNAL STRING FUNCTION OUTP_CODE39(STRING, LONG, LONG)
	EXTERNAL STRING FUNCTION ZIPC_BARCODE(STRING)

	!
	! Subroutine Definitions
	!
	! Always include complete definition of parameters for
	! better error detection.
	!
	EXTERNAL SUB ASSG_BATCH(LONG, STRING, STRING, STRING, STRING, &
		STRING, STRING, STRING, STRING, LONG)
	EXTERNAL SUB ASSG_CHANNEL(LONG, LONG)
	EXTERNAL SUB ASSG_FREECHANNEL(LONG)
	EXTERNAL SUB ASSG_UNMAKEBATCH(STRING, STRING, STRING)
	EXTERNAL SUB DSPL_SPLITCURSOR(STRING, LONG, LONG)
	EXTERNAL SUB ENTR_3BADKEY(SCOPE_STRUCT, LONG)
	EXTERNAL SUB ENTR_3MESSAGE(SCOPE_STRUCT, STRING, LONG)
	EXTERNAL SUB ENTR_3MESSAGENEWWINDOW(SCOPE_STRUCT, STRING, LONG)
	EXTERNAL SUB HELP_34MESSAGE(SCOPE_STRUCT, STRING, &
		STRING, STRING, STRING, STRING)
	EXTERNAL SUB FIND_FILE(STRING, STRING DIM(), LONG, STRING, STRING)
	EXTERNAL SUB HELP_MENUHELPKEY(STRING, STRING, STRING, STRING, &
		STRING, STRING, STRING, LONG)
	EXTERNAL SUB HELP_SPELL(STRING, STRING)
	EXTERNAL SUB LIBR_FORMATTEXT(STRING, LONG, LONG, STRING DIM ())
	EXTERNAL SUB MENU_3INTERRUPT(SCOPE_STRUCT)
	EXTERNAL SUB NOTE_PAD(STRING, STRING, STRING, LONG, STRING, LONG)
	EXTERNAL SUB READ_CODELIST(STRING, STRING, STRING DIM (), LONG)
	EXTERNAL SUB READ_CURPROTECTION(STRING, LONG)
	EXTERNAL SUB READ_DEVICE(STRING, STRING, LONG)
	EXTERNAL SUB READ_INITIALIZE()
	EXTERNAL SUB READ_PROTECTION(STRING, STRING, LONG)
	EXTERNAL SUB READ_QUEFORM(STRING, STRING DIM(,), LONG)
	EXTERNAL SUB SUBR_3EXITPROGRAM(SCOPE_STRUCT, STRING, STRING)
	EXTERNAL SUB SUBR_3SPAWN(SCOPE_STRUCT, STRING)
	EXTERNAL SUB SUBR_SUBMIT(STRING, LONG)
	EXTERNAL SUB WRIT_CURPROTECTION(STRING, LONG)
	EXTERNAL SUB WRIT_STRING(STRING, STRING)

#endif
