	!=======================================================================
	! 5900-5999	JC * Job Costing System
	! This include file is used to DECLARE window numbers for JC system
	!=======================================================================

	DECLARE LONG CONSTANT JC_MAIN_JOB.ID			= 5900%
	DECLARE LONG CONSTANT JC_MAIN_CONTROL.ID		= 5910%
	DECLARE LONG CONSTANT JC_MAIN_BALANCE.ID		= 5920%
	DECLARE LONG CONSTANT JC_MAIN_TYPE.ID	        	= 5921%
	DECLARE LONG CONSTANT JC_MAIN_CLASS.ID	        	= 5922%
	DECLARE LONG CONSTANT JC_MAIN_ACCOUNT.ID	        = 5930%

