	!=======================================================================
	! 9600-9699	OS * Order SignSystem
	! This include file is used to DECLARE window numbers for AR system
	!=======================================================================

	DECLARE LONG CONSTANT OS_MAIN_JOURNAL.ID		= 9600%
	DECLARE LONG CONSTANT OS_MAIN_JMAIN.ID			= 9601%
	DECLARE LONG CONSTANT OS_MAIN_JLINE.ID			= 9602%
	DECLARE LONG CONSTANT OS_MAIN_REGHEADER.ID		= 9603%
	DECLARE LONG CONSTANT OS_MAIN_BOM_LINE.ID		= 9604%

