	!=======================================================================
	! 8300-8399	PC * Price & Cost System
	! This include file is used to DECLARE window numbers for PC system
	!=======================================================================

	DECLARE LONG CONSTANT PC_MAIN_COST.ID			= 8300%
	DECLARE LONG CONSTANT PC_MAIN_COSTSCAN.ID		= 8305%
	DECLARE LONG CONSTANT PC_MAIN_PRCTYPE.ID		= 8310%
	DECLARE LONG CONSTANT PC_MAIN_PRICE.ID			= 8315%
	DECLARE LONG CONSTANT PC_MAIN_PRICESCAN.ID		= 8320%
	DECLARE LONG CONSTANT PC_MAIN_DEAL.ID			= 8325%
	DECLARE LONG CONSTANT PC_MAIN_DEAL_PRODUCT.ID		= 8330%
