	!=======================================================================
	! 9100-9199	PS * Point Of Sale System
	! This include file is used to DECLARE window numbers for PS system
	!=======================================================================

	DECLARE LONG CONSTANT PS_MAIN_TICKETJOUR.ID		= 9110%
	DECLARE LONG CONSTANT PS_MAIN_TICKETLINE.ID		= 9115%
	DECLARE LONG CONSTANT PS_MAIN_CONTROL.ID		= 9130%
	DECLARE LONG CONSTANT PS_MAIN_CASHREG.ID		= 9135%
	DECLARE LONG CONSTANT PS_MAIN_CASHINOUT.ID		= 9140%
	DECLARE LONG CONSTANT PS_MAIN_REGHEADER.ID 		= 9160%
	DECLARE LONG CONSTANT PS_MAIN_REGLINE.ID 		= 9165%
	DECLARE LONG CONSTANT PS_MAIN_QUERYLINE.ID 		= 9188%
