	!=======================================================================
	! 4300-4399	AR * Accounts Recivable System
	! This include file is used to DECLARE window numbers for AR system
	!=======================================================================

	DECLARE LONG CONSTANT PW_MAIN_PWH.ID			= 4300%
	DECLARE LONG CONSTANT PW_MAIN_PWL1.ID			= 4301%
	DECLARE LONG CONSTANT PW_MAIN_PWL2.ID			= 4302%

