	!=======================================================================
	! 8400-8499	RM * Restaurant Management System
	! This include file is used to DECLARE window numbers for RM system
	!=======================================================================


	DECLARE LONG CONSTANT RM_MAIN_CONTROL.ID		= 8405%
	DECLARE LONG CONSTANT RM_MAIN_HISTORY.ID		= 8410%
	DECLARE LONG CONSTANT RM_MAIN_JOURNAL.ID		= 8415%
	DECLARE LONG CONSTANT RM_MAIN_JOURPOST.ID		= 8420%
	DECLARE LONG CONSTANT RM_MAIN_JOURPROD.ID		= 8425%
	DECLARE LONG CONSTANT RM_MAIN_TRANSFLAG.ID		= 8435%
	DECLARE LONG CONSTANT RM_MAIN_TRANSFLAGSCAN.ID		= 8440%
	DECLARE LONG CONSTANT RM_MAIN_TRANSACTION.ID		= 8450%
