	!=======================================================================
	! 8900-8999	SB * Sub Ledger System
	! This include file is used to DECLARE window numbers for SB system
	!=======================================================================

	DECLARE LONG CONSTANT SB_MAIN_BALANCE.ID		= 8900%
	DECLARE LONG CONSTANT SB_MAIN_BUDGET.ID			= 8905%
	DECLARE LONG CONSTANT SB_MAIN_SUBACCOUNT.ID		= 8910%
	DECLARE LONG CONSTANT SB_MAIN_SYSTEM.ID			= 8915%
	DECLARE LONG CONSTANT SB_MAIN_TYPE.ID			= 8935%
	DECLARE LONG CONSTANT SB_MAIN_CLASS.ID			= 8940%
	DECLARE LONG CONSTANT SB_MAIN_ACCOUNT.ID		= 8945%

