	!=======================================================================
	! 6300-6399	SR * Service Request System
	! This include file is used to DECLARE window numbers for SR system
	!=======================================================================

	DECLARE LONG CONSTANT SR_MAIN_REQUEST.ID		= 6305%
	DECLARE LONG CONSTANT SR_MAIN_LABOR.ID			= 6310%
	DECLARE LONG CONSTANT SR_MAIN_MATERIAL.ID		= 6315%

