	!=======================================================================
	! 7100-7199	SS * Support System
	! This include file is used to DECLARE window numbers for SS system
	!=======================================================================

	DECLARE LONG CONSTANT SS_MAIN_CUSTOM.ID			= 7105%
	DECLARE LONG CONSTANT SS_MAIN_CUS_SYSMENU.ID		= 7110%
	DECLARE LONG CONSTANT SS_MAIN_LICENSE.ID		= 7115%

