10	  ! &
	  ! Program name: araged		Compiled with SCALE 0 on V09.3 &
	  ! Decompiled on 21-Dec-16 at 05:12 PM
30	  ON ERROR GOTO 19000 &
	\ JUNK$=SYS(CHR$(6%)+CHR$(-7%)) &
	\ TEMP$=SYS(CHR$(12%)) &
	\ PRJPRG$=MID(TEMP$,23%,1%)+MID(TEMP$,24%,1%)+NUM1$(ASCII(MID(TEMP$,25%,1%)))+":"+"["+NUM1$(ASCII(MID(TEMP$,6%,1%)))+","+NUM1$(ASCII(MID(TEMP$,5%,1%)))+"]"+RAD$(ASCII(MID(TEMP$,7%,1%))+SWAP%(ASCII(MID(TEMP$,8%,1%))))+RAD$(ASCII(MID(TEMP$,9%,1%))+SWAP%(ASCII(MID(TEMP$,10%,1%))))+"."+RAD$(ASCII(MID(TEMP$,11%,1%))+SWAP%(ASCII(MID(TEMP$,12%,1%)))) &
	\ JUNK$=SYS(CHR$(6%)+CHR$(9%)) &
	\ JJ%=ASCII(LEFT(JUNK$,1%))/2% &
	\ JJ$=RIGHT(NUM1$(JJ%+100%),2%)
60	  CH%,OUTPUT.CH%=1% &
	\ OPEN "KB:" AS FILE 1%, MODE 8%+256%
70	  ESC$=CHR$(155%) &
	\ CLSCN$=ESC$+"[H"+ESC$+"[J" &
	\ COLM.ON$=ESC$+"[?3h" &
	\ COLM.OFF$=ESC$+"[?3l" &
	\ R.ON$=ESC$+"[7m" &
	\ G.OFF$=ESC$+"[m" &
	\ CLRLIN$=ESC$+"[2K" &
	\ ENTER.COPY$=ESC$+"[5i" &
	\ EXIT.COPY$=ESC$+"[4i"
80	  DROP.DEAD.DATE$="        " &
	\ VERSION.NO$="V1.0" &
	\ DATE.TIME$=SYS(CHR$(6%)+CHR$(20%)+CHR$(0%)+CHR$(0%)+CHR$(1%)+CHR$(SWAP%(1%))+STRING$(11%,0%)+CHR$(SWAP%(0%))+CHR$(1%)+CHR$(SWAP%(1%))) &
	\ IF DROP.DEAD.DATE$<>"" THEN  &
		  IF DROP.DEAD.DATE$<MID(SYS(DATE.TIME$),7%,8%) THEN  &
			  MESG$=MID(SYS(CHR$(6%)+CHR$(9%)+CHR$(47%)),3%,30%) &
			\ PRINT #CH%, MESG$; &
			\ V$=SYS(CHR$(9%))
100	  DIM CUS.TYPE$(20%), TOTAL(20%,5%) &
	\ DEVICE.CH%,PRNT.TMP%=2% &
	\ AGEDAY.CH%=2% &
	\ APCCTL.CH%=2% &
	\ ARREG.CH%=2% &
	\ TEMP.CH%=4% &
	\ CUSTOM.CH%=8% &
	\ CUSBAL.CH%=6% &
	\ MENU.CH%=12%
120	  OPEN "PRNT"+JJ$+".TMP" FOR INPUT AS FILE PRNT.TMP% &
	\ NEXT.REPORT%=0% &
	\ CHAIN.PROGRAM$="" &
	\ CHAIN.LINE%=0%
130	  INPUT LINE #PRNT.TMP%, A$ &
	\ PR$=LEFT(A$,2%) &
	\ CMD$=CVT$$(RIGHT(A$,4%),140%) &
	\ IF PR$="RN" THEN  &
		  IF NEXT.REPORT% THEN &
			  GOTO 160 &
		  ELSE &
			  NEXT.REPORT%=-1%
140	  LIN.PER.PAGE%=VAL(CMD$) IF PR$="LP" &
	\ SPAGE%=VAL(CMD$) IF PR$="SP" &
	\ EPAGE%=VAL(CMD$) IF PR$="EP" &
	\ COPIES%=VAL(CMD$) IF PR$="CP" &
	\ REPDATE$=CMD$ IF PR$="RD" &
	\ DISPLAY$=CMD$ IF PR$="DP" &
	\ AUTOSCROLL$=CMD$ IF PR$="AS" &
	\ SPOOLR$=CMD$ IF PR$="SL" &
	\ OUTDEV$=CMD$ IF PR$="OD" &
	\ MS$=CMD$ IF PR$="MS" &
	\ U1$=CMD$ IF PR$="U1" &
	\ U2$=CMD$ IF PR$="U2" &
	\ U3$=CMD$ IF PR$="U3" &
	\ U4$=CMD$ IF PR$="U4" &
	\ U5$=CMD$ IF PR$="U5" &
	\ IF PR$="PC" THEN  &
		  TEMP%=1% &
		\ TEMP%=2% IF LEFT(CMD$,1%)="\" &
		\ PC$=PC$+CHR$(VAL(MID(CMD$,TEMP%+(LOOP%-1%)*4%,3%))) FOR LOOP%=1% TO LEN(CMD$)/4%
150	  GOTO 130
160	  GOTO 190 IF CHAIN.FLAG%=0% AND U3$="S" &
	\ KILL "PRNT"+JJ$+".TMP" &
	\ GOTO 190 IF PR$<>"RN"
170	  OPEN "PRNT"+JJ$+".TMP" FOR OUTPUT AS FILE PRNT.TMP%+1% &
	\ CHAIN.LINE%=31000%
180	  PRINT #PRNT.TMP%+1%, A$; &
	\ INPUT LINE #PRNT.TMP%, A$ &
	\ CHAIN.PROGRAM$=CVT$$(RIGHT(A$,4%),140%) IF LEFT(A$,2%)="PG" AND CHAIN.PROGRAM$="" &
	\ GOTO 180
190	  CLOSE PRNT.TMP% &
	\ CLOSE PRNT.TMP%+1% &
	\ FROM.ITEM$="ALL" &
	\ FROM.ITEM$=U1$ IF U1$<>"" &
	\ TO.ITEM$=U2$ &
	\ ORDER.KEY$=U3$ &
	\ CUS.LOC$=U4$ &
	\ TEMP$=U5$ &
	\ BASE.DAY=FNAGE(TEMP$)+1% &
	\ CUT.OFF%=FND6%(LEFT(TEMP$,2%)+"00"+MID(TEMP$,5%,2%)) &
	\ REPDATE$="Aged as of "+LEFT(TEMP$,2%)+"/"+MID(TEMP$,3%,2%)+"/"+RIGHT(TEMP$,5%)
200	  IF FNO%(DEVICE.CH%,"DEVICE.DAT","/RO","")=0% THEN  &
		  CUSTOM.DEVICE$=MID(FNL$,7%,20%)+"" IF FNG%(DEVICE.CH%,"CUSTOM")=0% &
		\ CUSBAL.DEVICE$=MID(FNL$,7%,20%)+"" IF FNG%(DEVICE.CH%,"CUSBAL")=0% &
		\ ARREG.DEVICE$=MID(FNL$,7%,20%)+" IF FNG%(DEVICE.CH%,"ARREG ")=0% &
		\ ARBAL.DEVICE$=MID(FNL$,7%,20%)+" IF FNG%(DEVICE.CH%,"ARBAL ")=0% &
		\ AGEDAY.DEVICE$=MID(FNL$,7%,20%)+"" IF FNG%(DEVICE.CH%,"AGEDAY")=0% &
		\ APCCTL.DEVICE$=MID(FNL$,7%,20%)+"" IF FNG%(DEVICE.CH%,"APCCTL")=0% &
		\ V%=FNC%(DEVICE.CH%)
210	  CUSTOM.TEMP$="CUSTOM.DAT" &
	\ WORK.TEMP$="CUSTOM.DAS" &
	\ CUSTOM.TEMP$=WORK.TEMP$ IF CHAIN.FLAG% &
	\ IF ORDER.KEY$<>"S" THEN &
		  PAR.LEN%=6% &
	  ELSE &
		  PAR.LEN%=15%
220	  GOTO 300 IF ORDER.KEY$<>"S" OR CHAIN.FLAG%
227	  IF FNO%(CUSTOM.CH%,CUSTOM.DEVICE$+"CUSTOM.DAT","/RO","") THEN  &
		  V$=FNMESS$(CH%,FNS%,"CUSTOM.DAT",0%,-1%) &
		\ GOTO 1045
228	  V%=FNG%(CUSTOM.CH%,"")
230	  END.RECORD%=FNT &
	\ OPEN WORK.TEMP$ FOR OUTPUT AS FILE TEMP.CH% &
	\ DIM #4%, SORT.KEY$(32767%)=32% &
	\ SORT.KEY$(END.RECORD%)="" &
	\ SORT.KEY$(0%)=CVT%$(END.RECORD%)+CVT%$(22%)+"U" &
	\ RECORD.COUNT%=1%
240	  PRINT #CH%, RECORD 256%,CHR$(129%); &
	\ GET #CH%, RECORD 8192%
250	  FIELD #CH%, RECOUNT AS TEST$ &
	\ GOTO 17500 IF INSTR(1%,TEST$,CHR$(3%))
260	  POINTER%=FNR(CUSTOM.CH%+1%) &
	\ FIELD #CUSTOM.CH%+1%, FNL% AS TEMP$,6% AS CUSTOM.CUSNUM$,138% AS TEMP$,14% AS CUSTOM.ALPHA$ &
	\ SORT.KEY$(RECORD.COUNT%)=CUSTOM.ALPHA$+CUSTOM.CUSNUM$+CVT%$(POINTER%) &
	\ RECORD.COUNT%=RECORD.COUNT%+1% &
	\ IF FNN%(CUSTOM.CH%)=0% THEN  &
		  GOTO 240
285	  FOR LOOP%=RECORD.COUNT% TO END.RECORD% &
		\ SORT.KEY$(LOOP%)=SPACE$(20%)+CVT%$(-1%) &
	\ NEXT LOOP%
290	  CLOSE TEMP.CH% &
	\ Q0$=SYS(CHR$(7%)) &
	\ Q5%=INSTR(1%,Q0$,CHR$(255%)) &
	\ Q2%=INSTR(1%,Q0$,CHR$(14%)) &
	\ Q2%=Q5%+12% IF Q2%=0% &
	\ Q0$=MID(Q0$+SPACE$(12%),Q5%,Q2%-Q5%) IF Q5% &
	\ Q0$="" IF Q5%=0% &
	\ Q3$=CVT%$(30999%)+PRJPRG$ &
	\ Q3$=Q3$+"  " &
	\ Q9$=CHR$(13%)+WORK.TEMP$+CHR$(13%)+CHR$(13%)+Q0$+CHR$(14%) &
	\ Q$=LEFT(CHR$(LEN(Q3$))+Q3$+Q9$,127%) &
	\ Q$=SYS(CHR$(8%)+Q$) &
	\ CHAIN "ISM:FSTSRS.TSK" 0%
300	  IF FNO%(AGEDAY.CH%,AGEDAY.DEVICE$+"AGEDAY.DAS","/SF/RO","") OR FNG%(AGEDAY.CH%,"") THEN  &
		  DAYS%(I%)=30% FOR I%=1% TO 4% &
		\ SRVC.DAYS%=30% &
		\ GOTO 350
310	  FIELD #AGEDAY.CH%, FNL% AS JUNK$,1% AS DAYS$(1%),1% AS DAYS$(2%),1% AS DAYS$(3%),1% AS DAYS$(4%),1% AS DAYS$(5%) &
	\ DAYS%(I%)=ASCII(DAYS$(I%)) FOR I%=1% TO 4% &
	\ SRVC.DAYS%=ASCII(DAYS$(5%))
350	  V%=FNC%(AGEDAY.CH%) &
	\ FOR I%=1% TO 4% &
		\ BEG.DAY%=BEG.DAY%+DAYS%(I%-1%) &
		\ INTRVL$(I%)=NUM1$(BEG.DAY%+1%)+" to "+NUM1$(BEG.DAY%+DAYS%(I%)) &
		\ INTRVL$(I%)=SPACE$(11%-LEN(INTRVL$(I%)))+INTRVL$(I%) &
	\ NEXT I% &
	\ INTRVL$(5%)=NUM1$(BEG.DAY%+1%+DAYS%(4%))+" & Over" &
	\ INTRVL$(5%)=SPACE$(11%-LEN(INTRVL$(5%)))+INTRVL$(5%)
360	  DEFAULT.METHOD$="O" &
	\ IF FNO%(APCCTL.CH%,APCCTL.DEVICE$+"APCCTL.DAS","/SF/RO","")=0% THEN  &
		  IF FNG%(APCCTL.CH%,"ARL   ")=0% THEN  &
			  FIELD #APCCTL.CH%, FNL%+304% AS TEMP$,1% AS APCCTL.METHOD$ &
			\ IF APCCTL.METHOD$="O" OR APCCTL.METHOD$="B" THEN  &
				  DEFAULT.METHOD$=APCCTL.METHOD$+""
365	  V%=FNC%(APCCTL.CH%) &
	\ V%=FNO%(ARREG.CH%,ARREG.DEVICE$+"ARREG.DAT","/RO","")
370	  IF FNO%(CUSTOM.CH%,CUSTOM.DEVICE$+CUSTOM.TEMP$,"/RO","") THEN  &
		  V$=FNMESS$(CH%,FNS%,"CUSTOM.DAT",0%,-1%) &
		\ GOTO 17540
380	  CUSBAL.FLAG%=FNO%(CUSBAL.CH%,CUSBAL.DEVICE$+"CUSBAL.DAT","","")
400	  OPEN "MENU.FIL/RO" FOR INPUT AS FILE MENU.CH% &
	\ DIM #12%, A0$(1%)=64% &
	\ COMPANY$=CVT$$(RIGHT(A0$(1%),2%),128%) &
	\ CLOSE MENU.CH%
450	  !
510	  TITLE$="Customer Aging Detail Report" &
	\ PAGE.TOP$=STRING$(2%,10%)+CHR$(13%)+"Date: "+DATE$(0%)+SPACE$(50%-LEN(COMPANY$)/2%)+COMPANY$+SPACE$(58%-LEN(COMPANY$)/2%)+"Page <<###>>"+CHR$(10%)+CHR$(13%)+"Time: "+TIME$(0%)+SPACE$(51%-LEN(TITLE$)/2%)+TITLE$+SPACE$(58%-LEN(TITLE$)/2%)+"V1.0"+CHR$(10%)+CHR$(13%)+SPACE$(64%-LEN(REPDATE$)/2%)+REPDATE$+STRING$(2%,10%)+CHR$(13%)+STRING$(132%,ASCII("="))+CHR$(10%)+CHR$(13%) &
	\ PAGE.TOP1$="Cust # Customer Name"+SPACE$(14%)+"Phone         "+"Invoice#   Date  "+SPACE$(4%)+"Current"+INTRVL$(2%)+INTRVL$(3%)+INTRVL$(4%)+INTRVL$(5%)+"     Balance"+CHR$(10%)+CHR$(13%) &
	\ USE1$="\    \ \"+SPACE$(23%)+"\  \           \ \      \ \      \"+" #######.## #######.## #######.##"+" #######.## #######.## ########.##" &
	\ USE2$="\    \ \"+SPACE$(23%)+"\  \           \ \      \ \      \" &
	\ USE3$=" #######.##" &
	\ PAGE.BOT$=STRING$(3%,10%)+CHR$(13%) &
	\ BOT.MARGIN%=6% &
	\ MORE.LINES%=2% &
	\ DISPLAY.CONTROL%=18%
1045	  !
10000	  IF DISPLAY$<>"Y" THEN  &
		  CLOSE CH% &
		\ RESET.CH%=1% &
		\ TEMP.CH%=12% &
		\ OPEN OUTDEV$ AS FILE OUTPUT.CH%, MODE 2% &
		\ IF SPAGE%>1% THEN  &
			  OPEN "NL:" AS FILE TEMP.CH% &
			\ OUTPUT.CH%=TEMP.CH%
17000	  PAGE.BREAK%=LIN.PER.PAGE%-BOT.MARGIN% &
	\ START.TEMP$="" &
	\ START.TEMP$=FROM.ITEM$ IF FROM.ITEM$<>"ALL" &
	\ V%=FNG%(CUSTOM.CH%,START.TEMP$) &
	\ IF DISPLAY$="Y" THEN &
		  PRINT #OUTPUT.CH%, CLSCN$;COLM.ON$;R.ON$;PAGE.TOP1$;G.OFF$;FNSR$("2;22");FNP$("22;1"); &
	  ELSE &
		  PRINT #OUTPUT.CH%, ENTER.COPY$;PC$;FNPAGE$(LIN.PER.PAGE%,0%,1%,PAGE.TOP$+PAGE.TOP1$,""); &
		\ LINE.COUNT%=FNLINE%
17020	  GOTO 17500 IF FNR(CUSTOM.CH%+1%)=0%
17030	  FIELD #CUSTOM.CH%+1%, FNL% AS JUNK$,6% AS CUSTOM.NUM$,25% AS CUSTOM.NAME$,25% AS CUSTOM.ADD1$,21% AS CUSTOM.ADD2$,15% AS CUSTOM.CITY$,2% AS CUSTOM.STATE$,5% AS CUSTOM.COUNTRY$,10% AS CUSTOM.ZIP$,10% AS CUSTOM.PHONE$,2% AS CUSTOM.SLSMAN$,2% AS CUSTOM.TERR$,2% AS CUSTOM.LOC$,2% AS CUSTOM.TYPE$,2% AS CUSTOM.CODE$,1% AS CUSTOM.TAXFLG$,10% AS CUSTOM.STAXNUM$,2% AS CUSTOM.STAXLOC$,1% AS CUSTOM.METHOD$,1% AS CUSTOM.STMFLG$,15% AS CUSTOM.ALPSRT$ &
	\ GOTO 17395 IF FNCOMP%(LOC$,CUS.LOC$)=0% AND CUS.LOC$<>"" &
	\ TEST.CUSNUM$=CUSTOM.NUM$+"" &
	\ GOTO 17410 IF TEST.CUSNUM$>TO.ITEM$ AND TO.ITEM$<>"" &
	\ WORK.NAME$=CUSTOM.NAME$+"" &
	\ WORK.NUM$=CUSTOM.NUM$+"" &
	\ WORK.PHONE$=FNFONE$(CUSTOM.PHONE$)+"" &
	\ CUS.NAM$=CUSTOM.NAME$+"" &
	\ METHOD$=CUSTOM.METHOD$+"" &
	\ METHOD$=DEFAULT.METHOD$ IF METHOD$<>"B" AND METHOD$<>"O" &
	\ AGE(LOOP%)=0. FOR LOOP%=1% TO 6% &
	\ INV.AMT=0. &
	\ TEST.INVNUM$="" &
	\ UNAPPLY%=0% &
	\ ROA,ACC.BAL=0. &
	\ IF METHOD$="B" THEN  &
		  IF FNG%(CUSBAL.CH%,TEST.CUSNUM$)=0% THEN  &
			  FIELD #CUSBAL.CH%+1%, FNL% AS JUNK$,14% AS JUNK$,8% AS CUSBAL.CUR$,8% AS CUSBAL.30$,8% AS CUSBAL.60$,8% AS CUSBAL.90$,8% AS CUSBAL.OVER$,8% AS CUSBAL.YTDSER$,2% AS CUSBAL.LSTCHRG$,2% AS CUSBAL.LSTPYMT$,8% AS CUSBAL.LIMIT$,2% AS CUSBAL.UPDDAT$,8% AS CUSBAL.SVCBAL$ &
			\ AGE(1%)=0. &
			\ AGE(2%)=CVT$F(CUSBAL.CUR$) &
			\ AGE(3%)=CVT$F(CUSBAL.30$) &
			\ AGE(4%)=CVT$F(CUSBAL.60$) &
			\ AGE(5%)=CVT$F(CUSBAL.90$)+CVT$F(CUSBAL.OVER$) &
			\ AGE(6%)=CVT$F(CUSBAL.SVCBAL$)
17040	  V%=FNG%(ARREG.CH%,TEST.CUSNUM$) &
	\ GOSUB 18100 IF V% &
	\ GOSUB 18000 IF V% &
	\ GOTO 17395 IF V%
17060	  FIELD #ARREG.CH%+1%, FNL% AS TEMP$,6% AS ARREG.CUSNUM$,8% AS ARREG.INVNUM$,2% AS ARREG.TRATYP$,2% AS ARREG.TRADAT$,8% AS ARREG.SALAMT$,8% AS ARREG.DISAMT$,8% AS ARREG.OTHCHG$,8% AS ARREG.RECNUM$,6% AS ARREG.CHKNUM$,8% AS ARREG.ARACCT$,6% AS ARREG.CROSS$,25% AS ARREG.DESC$,2% AS ARREG.UPDATE$ &
	\ IF ARREG.CUSNUM$<>TEST.CUSNUM$ THEN  &
		  GOSUB 18100 &
		\ GOSUB 18000 &
		\ GOTO 17395
17070	  WORK.DATE$=FND6$(CVT$%(ARREG.UPDATE$)) &
	\ WORK.DATE$=LEFT(WORK.DATE$,2%)+"00"+RIGHT(WORK.DATE$,5%) &
	\ GOTO 17390 IF FND6%(WORK.DATE$)>CUT.OFF% AND CUT.OFF%<>0% AND FND6%(WORK.DATE$)<>0% &
	\ GOTO 17390 IF ARREG.TRATYP$="02" AND ARREG.CUSNUM$=TEST.CUSNUM$ &
	\ AMOUNT=CVT$F(ARREG.SALAMT$) &
	\ IF METHOD$="B" THEN  &
		  ROA=ROA-AMOUNT IF ARREG.TRATYP$="03" &
		\ AGE(1%)=AGE(1%)+AMOUNT IF ARREG.TRATYP$<>"03" AND LEFT(CVT$$(ARREG.INVNUM$,-1%),2%)<>"SC" &
		\ AGE(6%)=AGE(6%)+AMOUNT IF ARREG.TRATYP$<>"03" AND LEFT(CVT$$(ARREG.INVNUM$,-1%),2%)="SC" &
		\ INV.AMT=INV.AMT-AMOUNT IF ARREG.TRATYP$="03" &
		\ INV.AMT=INV.AMT+AMOUNT IF ARREG.TRATYP$<>"03" &
		\ GOTO 17390
17080	  IF ARREG.INVNUM$<>TEST.INVNUM$ THEN  &
		  UNAPPLY%=-1% &
		\ GOSUB 18100 &
		\ GOTO 17400 IF END.FLAG% &
		\ WORK.TRADAT$=ARREG.TRADAT$+"" &
		\ IF ARREG.TRATYP$<>"01" THEN &
			  AGE.DAY=0. &
		  ELSE &
			  AGE.DAY=BASE.DAY-FNAGE(FND6$(CVT$%(ARREG.TRADAT$))) &
			\ UNAPPLY%=0%
17090	  TEST.INVNUM$=ARREG.INVNUM$+"" &
	\ IF LEFT(CVT$$(ARREG.INVNUM$,-1%),2%)<>"SC" THEN  &
		  D%=6% &
		\ GOTO 17110
17095	  IF AMOUNT<0. AND UNAPPLY% THEN  &
		  ACC.BAL=ACC.BAL+AMOUNT IF AMOUNT<0. AND UNAPPLY% &
		\ INV.AMT=INV.AMT+AMOUNT IF AMOUNT<0. AND UNAPPLY% &
		\ GOTO 17390
17100	  IF AGE.DAY<=DAYS%(1%) THEN &
		  D%=1% &
	  ELSE &
		  IF AGE.DAY<=DAYS%(1%)+DAYS%(2%) THEN &
			  D%=2% &
		  ELSE &
			  IF AGE.DAY<=DAYS%(1%)+DAYS%(2%)+DAYS%(3%) THEN &
				  D%=3% &
			  ELSE &
				  IF AGE.DAY<=DAYS%(1%)+DAYS%(2%)+DAYS%(3%)+DAYS%(4%) THEN &
					  D%=4% &
				  ELSE &
					  D%=5%
17110	  AGE(D%)=AGE(D%)+AMOUNT &
	\ INV.AMT=INV.AMT+AMOUNT
17390	  IF FNN%(ARREG.CH%)=0% THEN &
		  GOTO 17060 &
	  ELSE &
		  GOSUB 18100 &
		\ GOSUB 18000
17395	  IF FNN%(CUSTOM.CH%)=0% THEN  &
		  GOTO 17030
17400	  GOSUB 18100 &
	\ GOSUB 18000
17410	  GOTO 17500 IF END.FLAG% &
	\ PRINT #OUTPUT.CH% &
	\ PRINT #OUTPUT.CH%, USING USE1$, "","GRAND TOTAL","","","",T(1%),T(2%),T(3%),T(4%),T(5%),T(1%)+T(2%)+T(3%)+T(4%)+T(5%) &
	\ LINE.COUNT%=LINE.COUNT%+2%
17500	  IF DISPLAY$<>"Y" THEN &
		  PRINT #OUTPUT.CH%, FNPAGE$(LIN.PER.PAGE%,LINE.COUNT%,FNPAGE%,"",PAGE.BOT$); &
	  ELSE &
		  PRINT #OUTPUT.CH%, FNP$("24;1");"End of report";FNP$("24;105");"Hit any key to continue"; &
		\ INP$=FNINP$(CH%,128%," ",1%,1%) &
		\ PRINT #OUTPUT.CH%, COLM.ON$;
17540	  KILL CUSTOM.DEVICE$+"CUSTOM.DAS"
17550	  PRINT #OUTPUT.CH%, EXIT.COPY$; IF DISPLAY$<>"Y" &
	\ PRINT #OUTPUT.CH%, FNSR$("1;24");COLM.OFF$; IF DISPLAY$="Y" &
	\ CLOSE OUTPUT.CH% &
	\ V%=FNX%(CHAIN.PROGRAM$,CHAIN.LINE%,"")
17600	  IF DISPLAY$<>"Y" AND LINE.COUNT%+MORE.LINES%>PAGE.BREAK% THEN  &
		  END.FLAG%=-1% IF PAGE%>=EPAGE% AND EPAGE%<>0% &
		\ RETURN IF END.FLAG% &
		\ PRINT #OUTPUT.CH%, FNPAGE$(LIN.PER.PAGE%,LINE.COUNT%,FNPAGE%,PAGE.TOP$+PAGE.TOP1$,PAGE.BOT$); &
		\ LINE.COUNT%=FNLINE% &
		\ IF SPAGE%>1% THEN  &
			  IF SPAGE%<=PAGE% THEN  &
				  OUTPUT.CH%=RESET.CH% &
				\ PRINT #OUTPUT.CH%, ENTER.COPY$;PC$;FNPAGE$(LIN.PER.PAGE%,0%,PAGE%,PAGE.TOP$+PAGE.TOP1$,""); &
				\ LINE.COUNT%=FNLINE% &
				\ SPAGE%=0%
17650	  IF DISPLAY$="Y" AND LINE.COUNT%>DISPLAY.CONTROL% THEN  &
		  PRINT #OUTPUT.CH%, FNP$("24;105");"Hit any key to continue"; &
		\ INP$=FNINP$(CH%,128%," ",1%,1%) &
		\ LINE.COUNT%=0% &
		\ PRINT #OUTPUT.CH%, FNP$("24;1");CLRLIN$;FNP$("21;132")
17670	  RETURN
18000	  FOR LOOP%=1% TO 6% &
		\ ACC.BAL=ACC.BAL+AGE(LOOP%) IF AGE(LOOP%)<0. &
		\ AGE(LOOP%)=0. IF AGE(LOOP%)<0. &
	\ NEXT LOOP% &
	\ IF AGE(6%)<>0. THEN  &
		  AGE(6%)=AGE(6%)+ACC.BAL &
		\ IF AGE(6%)>0. THEN &
			  ACC.BAL=0. &
		  ELSE &
			  ACC.BAL=AGE(6%) &
			\ AGE(6%)=0.
18005	  IF AGE(6%)<>0. THEN  &
		  TEMP=AGE(6%) &
		\ AGE(6%)=AGE(6%)-ROA &
		\ ROA=ROA-TEMP &
		\ IF AGE(6%)<=0. THEN &
			  AGE(6%)=0. &
		  ELSE &
			  ROA=0.
18007	  GOTO 18020 IF ACC.BAL=0. &
	\ FOR LOOP%=5% TO 1% STEP -1% &
		\ IF AGE(LOOP%)<>0. THEN  &
			  AGE(LOOP%)=AGE(LOOP%)+ACC.BAL &
			\ IF AGE(LOOP%)>0. THEN &
				  ACC.BAL=0. &
			  ELSE &
				  ACC.BAL=AGE(LOOP%) &
				\ AGE(LOOP%)=0.
18010			  NEXT LOOP% &
	\ AGE(1%)=AGE(1%)+ACC.BAL
18020	  GOTO 18050 IF METHOD$="O" &
	\ FOR LOOP%=5% TO 1% STEP -1% &
		\ GOTO 18050 IF ROA=0. &
		\ TEMP=AGE(LOOP%) &
		\ IF TEMP<>0. THEN  &
			  AGE(LOOP%)=AGE(LOOP%)-ROA &
			\ ROA=ROA-TEMP &
			\ IF AGE(LOOP%)<=0. THEN &
				  AGE(LOOP%)=0. &
			  ELSE &
				  ROA=0.
18030			  NEXT LOOP% &
	\ AGE(1%)=AGE(1%)-ROA
18050	  AGE(1%)=AGE(1%)+AGE(6%) &
	\ BALANC=0. &
	\ BALANC=BALANC+FNZ(AGE(LOOP%)) FOR LOOP%=1% TO 5% &
	\ BALANC=BALANC &
	\ GOTO 18090 IF BALANC=0.
18060	  PRINT #OUTPUT.CH%, USING USE1$, "","CUSTOMER TOTAL","","","",AGE(1%),AGE(2%),AGE(3%),AGE(4%),AGE(5%),BALANC &
	\ PRINT #OUTPUT.CH% &
	\ LINE.COUNT%=LINE.COUNT%+2% &
	\ GOSUB 17600 &
	\ T(LOOP%)=T(LOOP%)+AGE(LOOP%) FOR LOOP%=1% TO 5%
18090	  AGE(LOOP%)=0. FOR LOOP%=1% TO 6% &
	\ ROA,ACC.BAL=0. &
	\ RETURN
18100	  GOTO 18190 IF FNZ(INV.AMT)=0. &
	\ TRADAT$=FND6$(CVT$%(WORK.TRADAT$)) &
	\ TRADAT$=LEFT(TRADAT$,2%)+"/"+MID(TRADAT$,3%,2%)+"/"+RIGHT(TRADAT$,5%) &
	\ PRINT #OUTPUT.CH%, USING USE2$, WORK.NUM$,WORK.NAME$,WORK.PHONE$,TEST.INVNUM$,TRADAT$; &
	\ WORK.NUM$,WORK.NAME$,WORK.PHONE$="" &
	\ FOR LOOP%=1% TO 5% &
		\ PRINT #OUTPUT.CH%, USING USE3$, INV.AMT; IF D%=LOOP% &
		\ PRINT #OUTPUT.CH%, SPACE$(LEN(USE3$)); IF D%<>LOOP% &
	\ NEXT LOOP% &
	\ PRINT #OUTPUT.CH% &
	\ LINE.COUNT%=LINE.COUNT%+1% &
	\ GOSUB 17600
18190	  INV.AMT=0. &
	\ RETURN
18900	  !
19000	  RESUME 160 IF ERL=130% &
	\ RESUME 190 IF ERL=170% OR ERL=180% &
	\ RESUME 260 IF ERL=240% &
	\ RESUME 450 IF ERL=400% &
	\ RESUME 17540 IF ERR=54% &
	\ RESUME 17550 IF ERL=17540%
19010	  IF ERR=28% THEN  &
		  JUNK$=SYS(CHR$(6%)+CHR$(-7%)) &
		\ RESUME 17540
19015	  IF ERR=27% THEN  &
		  RESUME 70 IF ERL=60% &
		\ RESUME 18900
19100	  IF ERL=120% THEN  &
		  PRINT #CH%, FNP$("24;1");CLRLIN$;"Unable to find print control file.  Aborting";FNP$("24;55");"Hit any key to continue"; &
		\ INP$=FNINP$(CH%,128%," ",1%,0%) &
		\ RESUME 17500
19900	  ON ERROR GOTO 0
30000	  DEF FNINP$(CHN%,KYP%,FILLCHAR$,INPUTLEN%,TO.ERR%) &
	\ PRINT #CHN%, STRING$(INPUTLEN%,ASCII(FILLCHAR$));STRING$(INPUTLEN%,8%); &
	\ PRINT #CHN%, RECORD 256%,CHR$(KYP%+INPUTLEN%)+FILLCHAR$; &
	\ GET #CHN% &
	\ FIELD #CHN%, RECOUNT AS BUFFER$ &
	\ BUFFER$="%^C" IF INSTR(1%,BUFFER$,CHR$(3%)) &
	\ FNINP$=CVT$$(BUFFER$,4%) &
	\ V=SQR(-1.) IF BUFFER$="%^C" AND TO.ERR% &
	\ FNEND
30200	  DEF FNP$(ROWCOL$) &
	\ FNP$=ESC$+"["+ROWCOL$+"H" &
	\ FNEND
30250	  DEF FNMESS$(CHN%,ERRNUM%,DESC$,TO.ERR%,PRINT.TEST%) &
	\ MESG$=MID(SYS(CHR$(6%)+CHR$(9%)+CHR$(ERRNUM%)),3%,30%)+DESC$ &
	\ IF PRINT.TEST% THEN  &
		  PRINT #CHN%, FNP$("24;1");CLRLIN$;MESG$;FNP$("24;55");"Hit any key to continue."; &
		\ NW$=FNINP$(CHN%,128%," ",1%,TO.ERR%)
30260	  FNMESS$=MESG$ &
	\ FNEND
30300	  DEF FNSR$(BEGEND$) &
	\ FNSR$=ESC$+"["+BEGEND$+"r" &
	\ FNEND
30320	  DEF FNFONE$(PHN$) &
	\ FNFONE$="("+LEFT(PHN$,3%)+")"+MID(PHN$,4%,3%)+"-"+RIGHT(PHN$,7%) &
	\ FNEND
30400	  DEF FND8%(D8) &
	\ FND8%=D8 &
	\ FNEND
30410	  DEF FND6%(D9$) &
	\ FND6%=VAL(MID(D9$,3%,2%))+VAL(LEFT(D9$,2%))*32%+FND8%(VAL(RIGHT(D9$,5%)))*512% &
	\ FNEND
30420	  DEF FND6$(D9%) &
	\ FND6$=RIGHT(NUM1$((D9% AND 15%*32%)/32%+100%),2%)+RIGHT(NUM1$((D9% AND 31%)+100%),2%)+RIGHT(NUM1$((SWAP%(D9%) AND 254%)/2%+100%),2%) &
	\ FNEND
30500	  DEF FNZ(Y) &
	\ TEMP=Y &
	\ TEMP=-Y IF Y<0. &
	\ TEMP=INT(TEMP*100.+6.8213185310482798e-15)/100. &
	\ TEMP=-TEMP IF Y<0. &
	\ FNZ=TEMP &
	\ FNEND
30550	  DEF FNAGE(D9$) &
	\ YEAR=VAL(RIGHT(D9$,5%)) &
	\ MONTH=VAL(LEFT(D9$,2%)) &
	\ DAY=VAL(MID(D9$,3%,2%)) &
	\ DAY=DAY+(YEAR+0.)*0. &
	\ IF MONTH>2. THEN  &
		  DAY=DAY-INT(MONTH*-107376232.+1.0430812658057675e-08) &
		\ YEAR=YEAR+1.
30560	  FNAGE=MONTH*31.+INT((YEAR+0.)/4.)+DAY &
	\ FNEND
30600	  !
30610	  DEF FNPAGE$(Y0%,Y1%,Y2%,Y0$,Y1$) &
	\ Y2$="" &
	\ Y2$=STRING$(Y0%-(Y1%+LEN(XLATE(Y1$,STRING$(10%,0%)+CHR$(10%)))),10%) IF Y1$<>"" &
	\ PAGE.LINE%=LEN(XLATE(Y0$,STRING$(10%,0%)+CHR$(10%))) &
	\ Y%=INSTR(1%,Y1$+Y0$,"<<#") &
	\ Y3%=INSTR(1%,Y1$+Y0$,"#>>") &
	\ Y$=RIGHT(NUM1$(0.+Y2%),8%-(Y3%-Y%)) &
	\ Y3%=-3% IF Y%=0% &
	\ PRINT #OUTPUT.CH%, Y2$;LEFT(Y1$+Y0$,Y%-1%);Y$;RIGHT(Y1$+Y0$,Y3%+3%); &
	\ PAGE%=Y2% &
	\ FNEND
30650	  DEF FNPAGE% &
	\ FNPAGE%=PAGE%+1% &
	\ FNEND
30660	  DEF FNLINE% &
	\ FNLINE%=PAGE.LINE% &
	\ FNEND
30900	  DEF FNCOMP%(Y$,Y2$) &
	\ Y9%=0% &
	\ Y9%=-1% IF Y2$="*" &
	\ Y2$=Y2$+","
30920	  IF Y9%=0% THEN  &
		  Y1$=LEFT(Y2$,INSTR(1%,Y2$,",")-1%) &
		\ Y2$=RIGHT(Y2$,LEN(Y1$)+2%) &
		\ Y1%=INSTR(1%,Y1$,"/") &
		\ IF Y1%+INSTR(1%,Y1$,"?")=0% THEN &
			  Y9%=Y$=Y1$ &
		  ELSE &
			  IF Y1% THEN &
				  Y9%=LEFT(Y1$,Y1%-1%)<=Y$ AND Y$<=RIGHT(Y1$,Y1%+1%) &
			  ELSE &
				  CHANGE CVT$$(LEFT(Y$,30%),-1%) TO Y% &
				\ CHANGE CVT$$(LEFT(Y1$,30%),-1%) TO Y1% &
				\ GOTO 30930 IF (Y%(Y3%)<>Y1%(Y3%))-(Y1%(Y3%)=63%) FOR Y3%=1% TO Y1%(0%) &
				\ Y9%=-1%
30930	  IF Y2$<>"" AND Y9%=0% THEN &
		  GOTO 30920 &
	  ELSE &
		  FNCOMP%=Y9%
30940	  FNEND
30999	  CHAIN.FLAG%=-1%
31000	  GOTO 30
32767	  END
