1	!
	! Special program to generate PR_EMP_DATES records for each
	! employee that hasn't got one yet.
	!
	!	04/24/91 - Kevin Handy
	!

	OPTION SIZE = (INTEGER LONG, REAL GFLOAT)

	%INCLUDE "SOURCE:[PR.OPEN]PR_EMP_MASTER.HB"
	MAP (PR_EMP_MASTER) PR_EMP_MASTER_CDD PR_EMP_MASTER

	%INCLUDE "SOURCE:[PR.OPEN]PR_EMP_DATES.HB"
	MAP (PR_EMP_DATES) PR_EMP_DATES_CDD PR_EMP_DATES

	ON ERROR GOTO 19000

100	%INCLUDE "SOURCE:[PR.OPEN]PR_EMP_MASTER.OPN"

110	%INCLUDE "SOURCE:[PR.OPEN]PR_EMP_DATES.CRE"

1000	RESET #PR_EMP_MASTER.CH%

1010	GET #PR_EMP_MASTER.CH%, REGARDLESS

2000	FIND #PR_EMP_DATES.CH%, KEY #0% EQ PR_EMP_MASTER::EMPNUM + "AC", REGARDLESS

	GOTO 1010

2100	PR_EMP_DATES::EMPLOYEE	= PR_EMP_MASTER::EMPNUM
	PR_EMP_DATES::DATECD	= "AC"
	PR_EMP_DATES::DATEBEGIN	= PR_EMP_MASTER::HIREDAY
	PR_EMP_DATES::DATEEND	= PR_EMP_MASTER::TERMDAY
	PR_EMP_DATES::DESCR	= "FULL"

	PR_EMP_DATES::DATEBEGIN	= "" &
		IF PR_EMP_DATES::DATEBEGIN = "00000000"

	PR_EMP_DATES::DATEEND	= "" &
		IF PR_EMP_DATES::DATEEND = "00000000"


	PUT #PR_EMP_DATES.CH%

	GOTO 1010

3000	CLOSE #PR_EMP_MASTER.CH%
	CLOSE #PR_EMP_DATES.CH%

	GOTO 32767

	%PAGE

19000	!*******************************************************************
	! Error Trapping
	!*******************************************************************

	SELECT ERL
		CASE 1010%
			RESUME 3000

		CASE 2000%
			RESUME 2100

	END SELECT

	ON ERROR GOTO 0

32767	END
