
FORM NORMAL

TITLE


"<COMPANY124>"
"<REPORT124>"

"<PERIOD124>"

END
FORMAT 1 "                               \                                   \";/
"#,###,###,###.##",2,(0)       
FORMAT 2 "                                  \                                \";/
"                 ###,###,###.##",X,X
FORMAT 3 "                               \                                   \";/
"#,###,###,###.##",2,-(0)
FORMAT 4 "                                                                    ";/
" ---------------"
FORMAT 5 "                                                                    ";/
"                 --------------"
FORMAT 6 "                                                                    ";/
"                 =============="
FORMAT 7 "                               \                                   \";/
"#,###,###,###.##",X,X
PRINT TITLE
LAYOUT "$TITLE:132"
PRINT TAB(51);"******* ASSETS *******"
PRINT
PRINT TAB(24);"CURRENT ASSETS:"
LAYOUT "$BLANK:31,$TITLE:68,VDEBIT:84,VCREDIT:100"
PRINT AND SUM INTO T1 F1 AC****CA**
PRINT AND SUM INTO T1 F1 AC****AR**
PRINT AND SUM INTO T1 F1 AC****BD**
PRINT AND SUM INTO T1 F1 AC****AO**
PRINT AND SUM INTO T1 F1 AC****AF**
PRINT AND SUM INTO T1 F1 AC????IN??
PRINT AND SUM INTO T1 F1 AC****PP**
PRINT AND SUM INTO T1 F1 AC****OC**
PRINT F4
PRINT AND SUM INTO T2 F2,TOTAL CURRENT ASSETS,T1(1)
PRINT
LAYOUT "$TITLE:132"
PRINT TAB(24);"FIXED ASSETS:"
ADD T1=0
LAYOUT "$BLANK:31,$TITLE:68,VDEBIT:84,VCREDIT:100"
PRINT AND SUM INTO T1 F1 AF****LA**
PRINT AND SUM INTO T1 F1 AF****BD**
PRINT AND SUM INTO T1 F1 AF****FF**
PRINT AND SUM INTO T1 F1 AF****ME**
PRINT AND SUM INTO T1 F1 AF****TE**
PRINT AND SUM INTO T1 F1 AF****LI**
PRINT F4
PRINT F7,BALANCE,T1(1)
PRINT AND SUM INTO T1 F1 AF****DP**
PRINT F4
PRINT AND SUM INTO T2 F2,TOTAL FIXED ASSETS,T1(1)
PRINT
LAYOUT "$TITLE:132"
PRINT TAB(24);"OTHER ASSETS:"
ADD T1=0
LAYOUT "$BLANK:31,$TITLE:68,VDEBIT:84,VCREDIT:100"
PRINT AND SUM INTO T1 F1 AO****IV**
PRINT AND SUM INTO T1 F1 AO****LC**
PRINT F4
PRINT AND SUM INTO T2 F2,TOTAL OTHER ASSETS,T1(1)
PRINT F5
PRINT F2,    TOTAL ASSETS,T2(1)
PRINT F6
ADD T1=0
ADD T5=T2
ADD T2=0
PRINT PAGE
PRINT TITLE
PRINT
PRINT
LAYOUT "$TITLE:132"
PRINT TAB(41);"********* LIABILITIES AND EQUITY *********"
PRINT
PRINT TAB(24);"CURRENT LIABILITIES:"
LAYOUT "$BLANK:31,$TITLE:68,VDEBIT:84,VCREDIT:100"
PRINT AND SUM INTO T1 F3 LC****AP**
PRINT AND SUM INTO T1 F3 LC****AS**
PRINT AND SUM INTO T1 F3 LC****AT**
PRINT AND SUM INTO T1 F3 LC****AI**
PRINT F4
PRINT AND SUM INTO T2 F2,TOTAL CURRENT LIABILITIES,T1(1)
ADD T1=0
PRINT
LAYOUT "$TITLE:132"
PRINT TAB(24);"LONG-TERM LIABILITIES:"
LAYOUT "$BLANK:31,$TITLE:68,VDEBIT:84,VCREDIT:100"
PRINT AND SUM INTO T1 F3 LL****NP**
PRINT AND SUM INTO T1 F3 LL****NT**
PRINT AND SUM INTO T1 F3 LL****NO**
PRINT AND SUM INTO T1 F3 LL****MT**
PRINT AND SUM INTO T1 F3 LL****LC**
PRINT AND SUM INTO T1 F3 LL****LN**
PRINT AND SUM INTO T1 F3 LL****DT**
PRINT F4
PRINT AND SUM INTO T2 F2,TOTAL LONG-TERM LIABILITIES,T1(1)
ADD T1=0
PRINT
PRINT TAB(24);"STOCKHOLDERS EQUITY:"
LAYOUT "$BLANK:31,$TITLE:68,VDEBIT:84,VCREDIT:100"
PRINT AND SUM INTO T1 F3 OE****CM**
PRINT AND SUM INTO T1 F3 OE****CS**
PRINT AND SUM INTO T1 F3 OE****PS**
PRINT AND SUM INTO T1 F3 OE****RE**
ADD T6=T5-T2-T1
PRINT AND SUM INTO T1 F7,YEAR TO DATE EARNINGS,T6(1)
PRINT F4
PRINT F2,TOTAL EQUITY,T1(1)
PRINT F5
ADD T2=T2+T1
PRINT F2,     TOTAL LIABILITIES AND STOCKHOLDERS EQUITY,T2(1)
PRINT F6
END
