10	  ! &
	  ! Program name: rep5		Compiled with SCALE 0 on V09.3 &
	  ! Decompiled on 28-Nov-16 at 05:11 PM
30	  ON ERROR GOTO 19000 &
	\ JUNK$=SYS(CHR$(6%)+CHR$(-7%)) &
	\ TEMP$=SYS(CHR$(12%)) &
	\ PRJPRG$=MID(TEMP$,23%,2%)+NUM1$(ASCII(MID(TEMP$,25%,1%)))+":"+"["+NUM1$(ASCII(MID(TEMP$,6%,1%)))+","+NUM1$(ASCII(MID(TEMP$,5%,1%)))+"]"+RAD$(ASCII(MID(TEMP$,7%,1%))+SWAP%(ASCII(MID(TEMP$,8%,1%))))+RAD$(ASCII(MID(TEMP$,9%,1%))+SWAP%(ASCII(MID(TEMP$,10%,1%)))) &
	\ TEMP$=SYS(CHR$(6%)+CHR$(9%)) &
	\ JJ%=ASCII(LEFT(TEMP$,1%))/2% &
	\ JJ$=RIGHT(NUM1$(JJ%+100%),2%)
60	  CH%,OUTPUT.CH%=1% &
	\ OPEN "KB:" AS FILE 1%, MODE 8%+256%
70	  ESC$=CHR$(155%) &
	\ COLM.ON$=ESC$+"[?3h" &
	\ COLM.OFF$=ESC$+"[?3l" &
	\ R.ON$=ESC$+"[7m" &
	\ G.OFF$=ESC$+"[m" &
	\ CLRLIN$=ESC$+"[2K" &
	\ CLSCN$=ESC$+"[H"+ESC$+"[J" &
	\ ENTER.COPY$=ESC$+"[5i" &
	\ EXIT.COPY$=ESC$+"[4i" &
	\ HID.CURSOR$=ESC$+"[?25l"+ESC$+"[24;1h" &
	\ CUR.ON$=ESC$+"[?25h"
80	  DROP.DEAD.DATE$="        " &
	\ VERSION.NO$="V1.0" &
	\ DATE.TIME$=SYS(CHR$(6%)+CHR$(20%)+CHR$(0%)+CHR$(0%)+CHR$(1%)+CHR$(SWAP%(1%))+STRING$(11%,0%)+CHR$(SWAP%(0%))+CHR$(1%)+CHR$(SWAP%(1%))) &
	\ IF DROP.DEAD.DATE$<>"" THEN  &
		  IF DROP.DEAD.DATE$<MID(DATE.TIME$,7%,8%) THEN  &
			  MESG$=MID(SYS(CHR$(6%)+CHR$(9%)+CHR$(47%)),3%,30%) &
			\ PRINT #CH%, MESG$;SYS(CHR$(9%))
100	  DEVICE.CH%,PRNT.TMP%=2% &
	\ SYST.CH%=2% &
	\ MENU.CH%=12%
120	  OPEN "PRNT"+JJ$+".TMP" FOR INPUT AS FILE PRNT.TMP% &
	\ NEXT.REPORT%=0% &
	\ CHAIN.LINE%=0% &
	\ CHAIN.PROGRAM$=""
130	  INPUT LINE #PRNT.TMP%, TEMP$ &
	\ PR$=LEFT(TEMP$,2%) &
	\ CMD$=CVT$$(RIGHT(TEMP$,4%),140%) &
	\ IF PR$="RN" THEN  &
		  GOTO 160 IF NEXT.REPORT% &
		\ NEXT.REPORT%=-1%
140	  LIN.PER.PAGE%=VAL(CMD$) IF PR$="LP" &
	\ SPAGE%=VAL(CMD$) IF PR$="SP" &
	\ EPAGE%=VAL(CMD$) IF PR$="EP" &
	\ COPIES%=VAL(CMD$) IF PR$="CP" &
	\ REPDATE$=CMD$ IF PR$="RD" &
	\ DISPLAY$=CMD$ IF PR$="DP" &
	\ AUTOSCROLL$=CMD$ IF PR$="AS" &
	\ SPOOLR$=CMD$ IF PR$="SL" &
	\ OUTDEV$=CMD$ IF PR$="OD" &
	\ MS$=CMD$ IF PR$="MS" &
	\ UD1$=CMD$ IF PR$="U1" &
	\ UD2$=CMD$ IF PR$="U2" &
	\ UD3$=CMD$ IF PR$="U3" &
	\ UD4$=CMD$ IF PR$="U4" &
	\ UD5$=CMD$ IF PR$="U5" &
	\ IF PR$="PC" THEN  &
		  TEMP%=1% &
		\ TEMP%=2% IF LEFT(CMD$,1%)="\" &
		\ PC$=PC$+CHR$(VAL(MID(CMD$,TEMP%+(LOOP%-1%),3%))) FOR LOOP%=1% TO LEN(CMD$) STEP 4%
150	  GOTO 130
160	  GOTO 190 IF CHAIN.FLAG%=0% AND SRTKEY$="S" &
	\ KILL "PRNT"+JJ$+".TMP" &
	\ GOTO 190 IF PR$<>"RN"
170	  OPEN "PRNT"+JJ$+".TMP" FOR OUTPUT AS FILE PRNT.TMP%+1% &
	\ CHAIN.LINE%=31000%
180	  PRINT #PRNT.TMP%+1%, TEMP$ &
	\ INPUT LINE #PRNT.TMP%, TEMP$ &
	\ CHAIN.PROGRAM$=CVT$$(RIGHT(TEMP$,4%),140%) IF LEFT(TEMP$,2%)="PG" AND CHAIN.PROGRAM$="" &
	\ GOTO 180
190	  SYSNAM$=UD1$ &
	\ V%=FNC%(PRNT.TMP%)
200	  IF FNO%(DEVICE.CH%,"DEVICE.DAT","/RO","")=0% THEN  &
		  SYST.DEVICE$=MID(FNL$,7%,20%)+"" IF FNG%(DEVICE.CH%,"SYST")=0% &
		\ V%=FNC%(DEVICE.CH%)
300	  OPEN SYST.DEVICE$+CVT$$(SYSNAM$,-1%)+"/RO" AS FILE SYST.CH% &
	\ GOTO 400
400	  OPEN "MENU.FIL/RO" FOR INPUT AS FILE MENU.CH% &
	\ DIM #12%, A0$(1%)=64% &
	\ COMPANY$=CVT$$(RIGHT(A0$(1%),2%),128%) &
	\ CLOSE MENU.CH%
510	  PRINT.WIDTH%=80% &
	\ WIDTH%=PRINT.WIDTH%-40% &
	\ TITLE$=SYSNAM$ &
	\ TITLE$=LEFT(SPACE$((WIDTH%-LEN(TITLE$))/2%)+TITLE$+SPACE$(WIDTH%),WIDTH%) &
	\ PAGE.TOP$=CHR$(0%)+CHR$(13%)+"Page <<###>>"+TITLE$+"Date: "+DATE$(0%)+"  Time: "+TIME$(0%)+STRING$(2%,10%)+CHR$(13%) &
	\ BOT.MARGIN%=3% &
	\ PAGE.BOT$=STRING$(BOT.MARGIN%,10%)+CHR$(13%) &
	\ PAGE.BREAK%=LIN.PER.PAGE%-BOT.MARGIN% &
	\ MORE.LINES%=2% &
	\ DISPLAY.CONTROL%=15%
10000	  IF DISPLAY$<>"Y" THEN  &
		  CLOSE CH% &
		\ RESET.CH%=1% &
		\ TEMP.CH%=12% &
		\ OPEN OUTDEV$ AS FILE OUTPUT.CH%, MODE 2% &
		\ IF SPAGE%>1% THEN  &
			  OPEN "NL:" AS FILE TEMP.CH% &
			\ OUTPUT.CH%=TEMP.CH%
17000	  IF DISPLAY$="Y" THEN &
		  PRINT #OUTPUT.CH%, COLM.ON$;R.ON$;PAGE.TOP1$;G.OFF$;FNSR$("1;19");FNP$("19;01"); &
	  ELSE &
		  PRINT #OUTPUT.CH%, ENTER.COPY$;FNPAGE$(LIN.PER.PAGE%,0%,1%,PAGE.TOP$+PAGE.TOP1$,""); &
		\ LINE.COUNT%=FNLINE%
17030	  INPUT LINE #SYST.CH%, A$
17040	  IF CVT$$(A$,-1%)="%PAGE" AND LINE.COUNT%<>FNLINE% THEN  &
		  MORE.LINES%=100% &
		\ GOSUB 17600 &
		\ MORE.LINES%=2% &
		\ GOTO 17030
17050	  PRINT #OUTPUT.CH%, CVT$$(A$,128%); &
	\ LINE.COUNT%=LINE.COUNT%+1% &
	\ GOTO 17500 IF END.FLAG% &
	\ GOSUB 17600
17100	  GOTO 17030
17500	  IF DISPLAY$<>"Y" THEN &
		  PRINT #OUTPUT.CH%, FNPAGE$(LIN.PER.PAGE%,LINE.COUNT%,FNPAGE%,"",PAGE.BOT$); &
	  ELSE &
		  PRINT #OUTPUT.CH%, STRING$(11%-LINE.COUNT%,10%) &
		\ PRINT #OUTPUT.CH%, FNP$("24;1");"End of report";FNP$("24;45");"Hit any key to continue"; &
		\ INP$=FNINP$(CH%,128%," ",1%,1%)
17540	  !
17550	  PRINT #OUTPUT.CH%, EXIT.COPY$; IF DISPLAY$<>"Y" &
	\ PRINT #OUTPUT.CH%, FNSR$("1;24");COLM.OFF$; IF DISPLAY$="Y" &
	\ IF ANOTHER.REPORT.FLAG%=0% THEN  &
		  CLOSE OUTPUT.CH% &
		\ V%=FNX%("",0%,"") &
		\ GOTO 32767
17570	  END.FLAG%=0% &
	\ ANOTHER.REPORT.FLAG%=0% &
	\ GOTO 17000
17600	  IF DISPLAY$<>"Y" AND LINE.COUNT%+MORE.LINES%>PAGE.BREAK% THEN  &
		  END.FLAG%=-1% IF PAGE%>=EPAGE% AND EPAGE%<>0% &
		\ RETURN IF END.FLAG% &
		\ PRINT #OUTPUT.CH%, FNPAGE$(LIN.PER.PAGE%,LINE.COUNT%,FNPAGE%,PAGE.TOP$+PAGE.TOP1$+PAG.A$,PAGE.BOT$); &
		\ LINE.COUNT%=FNLINE% &
		\ IF SPAGE%>1% THEN  &
			  IF SPAGE%<=PAGE% THEN  &
				  OUTPUT.CH%=RESET.CH% &
				\ PRINT #OUTPUT.CH%, ENTER.COPY$;FNPAGE$(LIN.PER.PAGE%,0%,PAGE%,PAGE.TOP$+PAGE.TOP1$+PAG.A$,""); &
				\ LINE.COUNT%=FNLINE% &
				\ SPAGE%=0%
17650	  IF DISPLAY$="Y" AND LINE.COUNT%>DISPLAY.CONTROL% THEN  &
		  V$=FNMESS$(OUTPUT.CH%,0%,"",-1%,-1%) &
		\ LINE.COUNT%=0% &
		\ PRINT #OUTPUT.CH%, FNP$("24;1");CLRLIN$;FNP$("18;132")
17670	  RETURN
18000	  !
18900	  !
19000	  RESUME 17500 IF ERR=11% AND ERL=17030% &
	\ RESUME 17500 IF ERL=17000% &
	\ RESUME 510 IF ERL=400% &
	\ RESUME 17540 IF ERR=54% &
	\ RESUME 17550 IF ERL=17540% &
	\ RESUME 190 IF ERL=130% OR ERL=160% OR ERL=180% &
	\ IF ERR=28% THEN  &
		  JUNK$=SYS(CHR$(6%)+CHR$(-7%)) &
		\ RESUME 17500 IF OUTPUT.CH%=CH%
19010	  IF ERR=27% THEN  &
		  RESUME 70 IF ERL=60% &
		\ RESUME 18900
19020	  IF ERL=120% THEN  &
		  V$=FNMESS$(CH%,0%,"Missing print control file.  "+"Aborting",0%,-1%) &
		\ RESUME 17500
19900	  ON ERROR GOTO 0
30000	  DEF FNINP$(CHN%,KYP%,FILLCHAR$,INPUTLEN%,TO.ERR%) &
	\ PRINT #CHN%, STRING$(INPUTLEN%,ASCII(FILLCHAR$));STRING$(INPUTLEN%,8%); &
	\ PRINT #CHN%, RECORD 256%,CHR$(KYP%+INPUTLEN%)+FILLCHAR$; &
	\ GET #CHN% &
	\ FIELD #CHN%, RECOUNT AS BUFFER$ &
	\ BUFFER$="%^C" IF INSTR(1%,BUFFER$,CHR$(3%)) &
	\ FNINP$=CVT$$(BUFFER$,4%) &
	\ V=SQR(-1.) IF BUFFER$="%^C" AND TO.ERR% &
	\ FNEND
30200	  DEF FNP$(ROWCOL$) &
	\ FNP$=ESC$+"["+ROWCOL$+"H" &
	\ FNEND
30250	  DEF FNMESS$(CHN%,ERRNUM%,DESC$,TO.ERR%,PRINT.TEST%) &
	\ MESG$=MID(SYS(CHR$(6%)+CHR$(9%)+CHR$(ERRNUM%)),3%,30%)+DESC$ &
	\ IF PRINT.TEST% THEN  &
		  PRINT #CHN%, FNP$("24;1");CLRLIN$;MESG$;FNP$("24;55");" Hit any key to continue"; &
		\ NW$=FNINP$(CHN%,128%," ",1%,TO.ERR%)
30260	  FNMESS$=MESG$ &
	\ FNEND
30300	  DEF FNSR$(BEGEND$) &
	\ FNSR$=ESC$+"["+BEGEND$+"r" &
	\ FNEND
30600	  DEF FNPAGE$(Y0%,Y1%,Y2%,Y0$,Y1$) &
	\ Y2$="" &
	\ Y2$=STRING$(Y0%-(Y1%+LEN(XLATE(Y1$,STRING$(10%,0%)+CHR$(10%)))),10%) IF Y1$<>"" &
	\ PAGE.LINE%=LEN(XLATE(Y0$,STRING$(10%,0%)+CHR$(10%))) &
	\ Y%=INSTR(1%,Y1$+Y0$,"<<#") &
	\ Y3%=INSTR(1%,Y1$+Y0$,"#>>") &
	\ Y$=RIGHT(NUM1$(0.+Y2%),8%-(Y3%-Y%)) &
	\ Y3%=-3% IF Y%=0% &
	\ PRINT #OUTPUT.CH%, Y2$;LEFT(Y1$+Y0$,Y%-1%);Y$;RIGHT(Y1$+Y0$,Y3%+3%); &
	\ PAGE%=Y2% &
	\ FNEND
30650	  DEF FNPAGE% &
	\ FNPAGE%=PAGE%+1% &
	\ FNEND
30660	  DEF FNLINE% &
	\ FNLINE%=PAGE.LINE% &
	\ FNEND
30900	  CHAIN.FLAG%=-1%
31000	  GOTO 30
32767	  END
